export const q_regulamentos_part2 = [
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 1 sobre regulamentos: O serviço de informação de voo de aeródromo é denominado pela sigla:',
    option_a: 'AFIS',
    option_b: 'TWR',
    option_c: 'ACC',
    option_d: 'APP',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'AFIS significa Aerodrome Flight Information Service.'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 2 sobre regulamentos: As regras de voo visual são identificadas pela sigla:',
    option_a: 'VFR',
    option_b: 'IFR',
    option_c: 'SVFR',
    option_d: 'IMC',
    correct_answer: 'a',
    difficulty: 'easy',
    explanation: 'VFR significa Visual Flight Rules.'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 3 sobre regulamentos: No plano de voo, a sigla EOBT significa:',
    option_a: 'Estimated Off-Block Time',
    option_b: 'Estimated On-Block Time',
    option_c: 'Estimated Over-Block Time',
    option_d: 'Estimated Out-Block Time',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'EOBT é o tempo estimado de calços fora.'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 4 sobre regulamentos: O órgão central do SISCEAB é o:',
    option_a: 'DECEA',
    option_b: 'ANAC',
    option_c: 'CENIPA',
    option_d: 'INFRAERO',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'O DECEA é o órgão central do Sistema de Controle do Espaço Aéreo Brasileiro.'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 5 sobre regulamentos: Qual é o documento que estabelece as regras do ar?',
    option_a: 'RBAC 91',
    option_b: 'RBAC 61',
    option_c: 'RBAC 135',
    option_d: 'RBAC 121',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'O RBAC 91 dita as regras gerais de operação para aeronaves civis.'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 6 sobre regulamentos: O espaço aéreo no qual é prestado o serviço de controle de aeródromo é a:',
    option_a: 'CTR',
    option_b: 'TMA',
    option_c: 'FIR',
    option_d: 'UTA',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'CTR (Control Zone) é a zona de controle associada a um aeródromo.'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 7 sobre regulamentos: A área de controle terminal é designada pela sigla:',
    option_a: 'TMA',
    option_b: 'CTR',
    option_c: 'UTA',
    option_d: 'CTA',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'TMA significa Terminal Control Area.'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 8 sobre regulamentos: A quem compete a investigação de acidentes aeronáuticos civis no Brasil?',
    option_a: 'CENIPA',
    option_b: 'ANAC',
    option_c: 'DECEA',
    option_d: 'Polícia Federal',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'O CENIPA é o órgão responsável pela investigação de acidentes aeronáuticos no Brasil.'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 9 sobre regulamentos: A fase de emergência caracterizada por apreensão quanto à segurança da aeronave e de seus ocupantes é a:',
    option_a: 'ALERFA',
    option_b: 'INCERFA',
    option_c: 'DETRESFA',
    option_d: 'MAYDAY',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'ALERFA é a fase de alerta, caracterizada por apreensão.'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 10 sobre regulamentos: A região de informação de voo é a:',
    option_a: 'FIR',
    option_b: 'TMA',
    option_c: 'CTR',
    option_d: 'UTA',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'FIR significa Flight Information Region.'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 11 sobre regulamentos: O espaço aéreo superior no Brasil inicia-se no nível de voo:',
    option_a: 'FL 245 exclusive',
    option_b: 'FL 195 exclusive',
    option_c: 'FL 245 inclusive',
    option_d: 'FL 195 inclusive',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'No Brasil, o espaço aéreo superior vai de FL 245 até ilimitado.'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 12 sobre regulamentos: A altitude de transição no Brasil, quando não publicada, é geralmente:',
    option_a: 'Varia conforme o aeródromo',
    option_b: 'Sempre 4000 ft',
    option_c: 'Sempre 5000 ft',
    option_d: 'Sempre 10000 ft',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'A altitude de transição é específica para cada aeródromo e publicada nas cartas.'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 13 sobre regulamentos: O código Q para pressão atmosférica ajustada ao nível médio do mar é:',
    option_a: 'QNH',
    option_b: 'QFE',
    option_c: 'QNE',
    option_d: 'QFF',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'O QNH fornece a altitude indicada ao nível médio do mar.'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 14 sobre regulamentos: A cor da luz que indica autorização para decolagem de uma aeronave no solo é:',
    option_a: 'Verde contínua',
    option_b: 'Branca contínua',
    option_c: 'Verde intermitente',
    option_d: 'Vermelha contínua',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Uma luz verde contínua direcionada à aeronave no solo significa autorização para decolar.'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 15 sobre regulamentos: A cor da luz que indica "Afaste-se da área de pouso em uso" para aeronave em voo é:',
    option_a: 'Vermelha intermitente',
    option_b: 'Vermelha contínua',
    option_c: 'Branca intermitente',
    option_d: 'Verde intermitente',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'Luz vermelha contínua para aeronave em voo significa Dê passagem a outra aeronave e continue no circuito.'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 16 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 16'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 17 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 17'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 18 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 18'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 19 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 19'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 20 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 20'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 21 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 21'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 22 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 22'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 23 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 23'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 24 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 24'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 25 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 25'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 26 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 26'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 27 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 27'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 28 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 28'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 29 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 29'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 30 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 30'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 31 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 31'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 32 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 32'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 33 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 33'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 34 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 34'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 35 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 35'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 36 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 36'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 37 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 37'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 38 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 38'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 39 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 39'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 40 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 40'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 41 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 41'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 42 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 42'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 43 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 43'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 44 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 44'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 45 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 45'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 46 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 46'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 47 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 47'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 48 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 48'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 49 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 49'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 50 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 50'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 51 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 51'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 52 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 52'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 53 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 53'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 54 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 54'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 55 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 55'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 56 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 56'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 57 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 57'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 58 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 58'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 59 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 59'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 60 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 60'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 61 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 61'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 62 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 62'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 63 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 63'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 64 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 64'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 65 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 65'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 66 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 66'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 67 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 67'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 68 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 68'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 69 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 69'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 70 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 70'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 71 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 71'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 72 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 72'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 73 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 73'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 74 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 74'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 75 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 75'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 76 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 76'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 77 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 77'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 78 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 78'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 79 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 79'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 80 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 80'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 81 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 81'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 82 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 82'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 83 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 83'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 84 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 84'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 85 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 85'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 86 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 86'
  },
  {
    bloco_id: 'regulamentos_de_trafego_aereo',
    text: 'Questão 87 sobre regulamentos',
    option_a: 'Opção correta',
    option_b: 'Opção incorreta',
    option_c: 'Opção incorreta',
    option_d: 'Opção incorreta',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Explicação para a questão 87'
  }
];
