export const q_tv_part3 = [
  {
    bloco_id: 'teoria_de_voo',
    text: 'A força aerodinâmica que se opõe ao peso de uma aeronave em voo reto e nivelado é a:',
    option_a: 'Tração.',
    option_b: 'Sustentação.',
    option_c: 'Gravidade.',
    option_d: 'Arrasto.',
    correct_answer: 'b',
    difficulty: 'easy',
    explanation: 'A sustentação atua para cima e se opõe ao peso, mantendo a aeronave em voo.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O ângulo formado pela corda da asa e a direção do vento relativo é o ângulo de:',
    option_a: 'Ataque.',
    option_b: 'Incidência.',
    option_c: 'Diedro.',
    option_d: 'Atitude.',
    correct_answer: 'a',
    difficulty: 'easy',
    explanation: 'O ângulo de ataque é o ângulo entre a corda do aerofólio e o vento relativo.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Qual das alternativas abaixo é uma superfície de controle primária?',
    option_a: 'Flap.',
    option_b: 'Trim tab.',
    option_c: 'Profundor.',
    option_d: 'Spoiler.',
    correct_answer: 'c',
    difficulty: 'easy',
    explanation: 'As superfícies de controle primárias são ailerons, profundor e leme de direção.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O movimento da aeronave em torno de seu eixo longitudinal é chamado de:',
    option_a: 'Arfagem.',
    option_b: 'Guinada.',
    option_c: 'Rolamento.',
    option_d: 'Derrapagem.',
    correct_answer: 'c',
    difficulty: 'easy',
    explanation: 'O rolamento (ou inclinação lateral) ocorre em torno do eixo longitudinal e é controlado pelos ailerons.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'A resistência ao avanço causada pela produção de sustentação é denominada arrasto:',
    option_a: 'Parasita.',
    option_b: 'Induzido.',
    option_c: 'De perfil.',
    option_d: 'De interferência.',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'O arrasto induzido é uma consequência direta da criação de sustentação pelas asas.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Para diminuir a velocidade de estol de uma aeronave, o piloto pode utilizar:',
    option_a: 'Spoilers.',
    option_b: 'Freios aerodinâmicos.',
    option_c: 'Flaps.',
    option_d: 'Compensadores.',
    correct_answer: 'c',
    difficulty: 'easy',
    explanation: 'Os flaps aumentam a sustentação e permitem que a aeronave voe a velocidades mais baixas sem estolar.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'A componente horizontal da sustentação durante uma curva é a força que causa a:',
    option_a: 'Arfagem.',
    option_b: 'Derrapagem.',
    option_c: 'Mudança de direção (curva).',
    option_d: 'Perda de altitude.',
    correct_answer: 'c',
    difficulty: 'medium',
    explanation: 'Quando a aeronave se inclina, a sustentação se divide em componentes vertical e horizontal; a horizontal faz a curva.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Qual é o eixo imaginário que passa do nariz à cauda da aeronave?',
    option_a: 'Vertical.',
    option_b: 'Lateral.',
    option_c: 'Transversal.',
    option_d: 'Longitudinal.',
    correct_answer: 'd',
    difficulty: 'easy',
    explanation: 'O eixo longitudinal estende-se do nariz à cauda.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O estol (perda de sustentação) ocorre sempre que o aerofólio excede o seu:',
    option_a: 'Ângulo de incidência crítico.',
    option_b: 'Ângulo de ataque crítico.',
    option_c: 'Fator de carga máximo.',
    option_d: 'Peso máximo de decolagem.',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'O estol ocorre quando o ângulo de ataque excede o limite crítico, descolando o fluxo de ar do extradorso da asa.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'A estabilidade que faz com que o avião retorne à sua atitude original após uma perturbação é chamada estabilidade:',
    option_a: 'Dinâmica.',
    option_b: 'Estática positiva.',
    option_c: 'Estática neutra.',
    option_d: 'Direcional.',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'Estabilidade estática positiva é a tendência inicial de retornar ao estado original.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O uso do leme de direção controla o movimento de:',
    option_a: 'Arfagem.',
    option_b: 'Rolagem.',
    option_c: 'Guinada.',
    option_d: 'Glissada.',
    correct_answer: 'c',
    difficulty: 'easy',
    explanation: 'O leme atua no eixo vertical, provocando o movimento de guinada.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Qual dispositivo serve para aliviar as forças nos comandos de voo?',
    option_a: 'Slot.',
    option_b: 'Slat.',
    option_c: 'Compensador (Trim tab).',
    option_d: 'Spoiler.',
    correct_answer: 'c',
    difficulty: 'easy',
    explanation: 'Os compensadores são pequenas superfícies que aliviam a pressão nos comandos mantendo-os na posição desejada.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'A força de sustentação atua sempre de forma perpendicular ao:',
    option_a: 'Solo.',
    option_b: 'Vento relativo.',
    option_c: 'Eixo longitudinal.',
    option_d: 'Eixo vertical.',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'A sustentação é definida como a força aerodinâmica perpendicular ao vento relativo.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'As partes constituintes do arrasto parasita são:',
    option_a: 'De forma, de atrito e de interferência.',
    option_b: 'Induzido e de perfil.',
    option_c: 'De compressibilidade e fricção.',
    option_d: 'De onda e sustentação.',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'O arrasto parasita não contribui para a sustentação e subdivide-se em forma, atrito e interferência.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O princípio físico que explica a geração de sustentação por diferenças de pressão é o de:',
    option_a: 'Newton.',
    option_b: 'Arquimedes.',
    option_c: 'Bernoulli.',
    option_d: 'Pascal.',
    correct_answer: 'c',
    difficulty: 'easy',
    explanation: 'O princípio de Bernoulli explica que o aumento da velocidade do fluido causa a diminuição da pressão estática.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Para um voo em subida com velocidade constante, a tração deve ser:',
    option_a: 'Igual ao arrasto.',
    option_b: 'Maior que o arrasto.',
    option_c: 'Igual ao peso.',
    option_d: 'Menor que a sustentação.',
    correct_answer: 'b',
    difficulty: 'hard',
    explanation: 'Na subida constante, a tração precisa vencer o arrasto e uma componente do peso.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'A velocidade de melhor ângulo de subida (Vx) proporciona:',
    option_a: 'A maior razão de ganho de altitude por tempo.',
    option_b: 'O maior ganho de altitude para uma dada distância horizontal.',
    option_c: 'O menor consumo de combustível.',
    option_d: 'A velocidade máxima de planeio.',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'Vx dá o melhor ganho de altitude em relação à distância percorrida no solo, útil para evitar obstáculos.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O deslocamento em torno do eixo lateral é comandado pelo(a):',
    option_a: 'Leme de direção.',
    option_b: 'Profundor.',
    option_c: 'Aileron.',
    option_d: 'Acelerador.',
    correct_answer: 'b',
    difficulty: 'easy',
    explanation: 'O profundor controla a arfagem (picada e cabrada), que ocorre em torno do eixo lateral.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'A razão entre a carga total suportada pelas asas e o peso total da aeronave é chamada de:',
    option_a: 'Carga alar.',
    option_b: 'Fator de carga.',
    option_c: 'Alongamento.',
    option_d: 'Carga de potência.',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'O fator de carga (G) é a proporção entre a sustentação produzida pelas asas e o peso da aeronave.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O aumento do ângulo de inclinação lateral em uma curva com altitude constante resultará em:',
    option_a: 'Diminuição do fator de carga.',
    option_b: 'Aumento da velocidade de estol.',
    option_c: 'Diminuição do peso aparente.',
    option_d: 'Aumento do raio de curva.',
    correct_answer: 'b',
    difficulty: 'hard',
    explanation: 'Um maior ângulo de inclinação aumenta o fator de carga, o que eleva a velocidade de estol.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'A linha reta imaginária que liga o bordo de ataque ao bordo de fuga de um aerofólio chama-se:',
    option_a: 'Linha de curvatura média.',
    option_b: 'Corda.',
    option_c: 'Eixo de arfagem.',
    option_d: 'Envergadura.',
    correct_answer: 'b',
    difficulty: 'easy',
    explanation: 'A corda é a linha reta imaginária entre o bordo de ataque e o bordo de fuga.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'A estabilidade longitudinal é determinada principalmente pelo:',
    option_a: 'Diedro das asas.',
    option_b: 'Enflechamento.',
    option_c: 'Centro de gravidade em relação ao centro de pressão.',
    option_d: 'Leme de direção.',
    correct_answer: 'c',
    difficulty: 'hard',
    explanation: 'A posição do CG em relação ao CP (ou foco aerodinâmico) define a estabilidade estática longitudinal do avião.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Um centro de gravidade (CG) localizado muito à frente do limite dianteiro fará a aeronave:',
    option_a: 'Tender a levantar o nariz exageradamente.',
    option_b: 'Ficar excessivamente instável.',
    option_c: 'Ter comandos de profundor "pesados" (dificuldade de cabrar).',
    option_d: 'Diminuir a velocidade de estol.',
    correct_answer: 'c',
    difficulty: 'medium',
    explanation: 'O CG muito à frente exige mais força no profundor para levantar o nariz e aumenta a velocidade de estol.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O estol sempre ocorre com o mesmo:',
    option_a: 'Peso.',
    option_b: 'Ângulo de ataque.',
    option_c: 'Fator de carga.',
    option_d: 'Velocidade indicada.',
    correct_answer: 'b',
    difficulty: 'easy',
    explanation: 'Independentemente do peso, velocidade ou atitude, o estol sempre ocorre quando se atinge o ângulo de ataque crítico.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'A aplicação de flap afeta o desempenho da aeronave pois:',
    option_a: 'Diminui a sustentação e o arrasto.',
    option_b: 'Aumenta a sustentação e o arrasto.',
    option_c: 'Aumenta a sustentação e diminui o arrasto.',
    option_d: 'Não afeta a sustentação, apenas o arrasto.',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'O flap altera a curvatura da asa, aumentando a sustentação e, consequentemente, o arrasto.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'A camada de ar que adere à superfície da asa, perdendo velocidade devido ao atrito, chama-se:',
    option_a: 'Camada turbulenta.',
    option_b: 'Camada limite.',
    option_c: 'Esteira de vórtices.',
    option_d: 'Vento relativo.',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'A camada limite é a fina camada de ar próxima à superfície da asa afetada pelo atrito.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Em uma asa, a região de menor pressão atmosférica em voo situa-se geralmente:',
    option_a: 'No intradorso.',
    option_b: 'No bordo de ataque.',
    option_c: 'No extradorso.',
    option_d: 'No bordo de fuga.',
    correct_answer: 'c',
    difficulty: 'medium',
    explanation: 'O fluxo de ar mais rápido sobre o extradorso (parte superior) cria uma área de baixa pressão (princípio de Bernoulli).'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O arrasto induzido pode ser minimizado por:',
    option_a: 'Superfícies mais lisas.',
    option_b: 'Aumento da velocidade.',
    option_c: 'Winglets na ponta das asas.',
    option_d: 'Uso de flaps em voo de cruzeiro.',
    correct_answer: 'c',
    difficulty: 'hard',
    explanation: 'Winglets ajudam a reduzir a força dos vórtices de ponta de asa, diminuindo o arrasto induzido.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'A razão entre a envergadura e a corda média geométrica de uma asa é chamada de:',
    option_a: 'Fator de carga.',
    option_b: 'Alongamento.',
    option_c: 'Carga alar.',
    option_d: 'Afilamento.',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'O alongamento (aspect ratio) é a relação entre a envergadura e a corda. Asas longas e estreitas têm alto alongamento.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O que ocorre com a velocidade de estol à medida que o peso da aeronave aumenta?',
    option_a: 'Diminui.',
    option_b: 'Aumenta.',
    option_c: 'Permanece a mesma.',
    option_d: 'Oscila dependendo da densidade.',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'Para gerar sustentação suficiente para um peso maior, a asa precisa de maior ângulo de ataque, atingindo o estol a uma velocidade superior.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Se o CG estiver muito recuado (próximo do limite traseiro), a aeronave apresentará:',
    option_a: 'Grande estabilidade longitudinal.',
    option_b: 'Menor sensibilidade nos comandos de arfagem.',
    option_c: 'Menor estabilidade longitudinal e risco de estol irreversível.',
    option_d: 'Dificuldade de tirar o avião do solo.',
    correct_answer: 'c',
    difficulty: 'hard',
    explanation: 'Um CG muito recuado diminui a estabilidade e torna perigosa a recuperação de estóis e parafusos.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Durante uma arremetida (go-around), a rápida aplicação de potência pode causar uma tendência de:',
    option_a: 'Guinada para a esquerda devido ao torque do motor.',
    option_b: 'O nariz baixar severamente.',
    option_c: 'Diminuição imediata da velocidade.',
    option_d: 'Aumento da eficiência do profundor, sem guinada.',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'O efeito de torque, a esteira de hélice espiralada e o fator P causam tendência de guinada à esquerda ao aplicar potência.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Para um voo horizontal e nivelado, a sustentação deve ser:',
    option_a: 'Maior que o peso.',
    option_b: 'Igual ao peso.',
    option_c: 'Menor que o peso.',
    option_d: 'Igual à tração.',
    correct_answer: 'b',
    difficulty: 'easy',
    explanation: 'Em voo reto e nivelado com velocidade constante, a sustentação equilibra o peso e a tração equilibra o arrasto.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Um avião que possui tendência natural de levantar a asa inclinada (retornar ao voo nivelado) possui boa estabilidade:',
    option_a: 'Longitudinal.',
    option_b: 'Lateral.',
    option_c: 'Direcional.',
    option_d: 'Dinâmica.',
    correct_answer: 'b',
    difficulty: 'easy',
    explanation: 'A estabilidade em torno do eixo longitudinal, que corrige a inclinação das asas, é a estabilidade lateral.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O dispositivo aerodinâmico que retarda o descolamento da camada limite em altos ângulos de ataque, situado no bordo de ataque, é o:',
    option_a: 'Trim tab.',
    option_b: 'Spoiler.',
    option_c: 'Slot/Slat.',
    option_d: 'Aileron.',
    correct_answer: 'c',
    difficulty: 'medium',
    explanation: 'Slots e slats direcionam o ar sob alta pressão para o extradorso, mantendo o fluxo aderido por mais tempo e permitindo maiores ângulos de ataque.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O fator de carga durante uma curva coordenada de 60 graus de inclinação é de aproximadamente:',
    option_a: '1 G.',
    option_b: '1.5 Gs.',
    option_c: '2 Gs.',
    option_d: '3 Gs.',
    correct_answer: 'c',
    difficulty: 'hard',
    explanation: 'O fator de carga é inversamente proporcional ao cosseno do ângulo de inclinação; cos(60) = 0.5, então o G é 1/0.5 = 2.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O que caracteriza a entrada em um parafuso (spin)?',
    option_a: 'Alta velocidade e baixo ângulo de ataque.',
    option_b: 'Estol assimétrico, onde uma asa estola antes ou mais severamente que a outra.',
    option_c: 'Aplicação excessiva de aileron em alta velocidade.',
    option_d: 'Curva coordenada com alto fator de carga.',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'O parafuso é uma manobra autorrotativa causada pelo estol agravado e assimétrico (guinada acoplada ao estol).'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'A recuperação padrão de um parafuso geralmente exige:',
    option_a: 'Leme no sentido contrário à rotação e profundor para frente para quebrar o estol.',
    option_b: 'Aileron totalmente contrário à curva e potência máxima.',
    option_c: 'Comandos neutros e potência máxima.',
    option_d: 'Leme no sentido da rotação e profundor cabrado.',
    correct_answer: 'a',
    difficulty: 'hard',
    explanation: 'Parar a guinada com o leme oposto e quebrar o estol diminuindo o ângulo de ataque é o procedimento base.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O vento relativo é sempre:',
    option_a: 'Paralelo à corda.',
    option_b: 'Oposto à trajetória de voo do avião.',
    option_c: 'Perpendicular à sustentação apenas em cruzeiro.',
    option_d: 'Produzido exclusivamente pelas hélices.',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'O vento relativo é o fluxo de ar que a aeronave experimenta, paralelo e em direção oposta à sua trajetória de voo real.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'A resistência do ar causada pelos suportes dos trens de pouso fixos é um exemplo de arrasto:',
    option_a: 'Induzido.',
    option_b: 'Parasita.',
    option_c: 'De compressibilidade.',
    option_d: 'De película.',
    correct_answer: 'b',
    difficulty: 'easy',
    explanation: 'O arrasto parasita inclui todo arrasto não relacionado à produção de sustentação, como trens de pouso fixos, antenas, etc.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Qual das alternativas abaixo ajuda a prover estabilidade lateral ao avião?',
    option_a: 'Leme de direção.',
    option_b: 'Diedro positivo das asas.',
    option_c: 'Posição avançada do CG.',
    option_d: 'Estabilizador horizontal.',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'O diedro positivo (asas inclinadas para cima) causa maior sustentação na asa abaixada, estabilizando lateralmente a aeronave.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Durante o voo lento, os comandos tornam-se "esponjosos" e respondem com atraso devido à:',
    option_a: 'Maior velocidade do ar passando sobre as superfícies.',
    option_b: 'Menor densidade do ar em baixas atitudes.',
    option_c: 'Menor fluxo de ar dinâmico passando sobre as superfícies de controle.',
    option_d: 'Ação exagerada do compensador.',
    correct_answer: 'c',
    difficulty: 'medium',
    explanation: 'A eficácia das superfícies de controle depende da pressão dinâmica; com velocidade baixa, os comandos perdem autoridade.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Para manter o avião coordenado, o piloto deve usar o leme para corrigir a guinada adversa, que é causada:',
    option_a: 'Pela diferença de arrasto entre os ailerons quando são defletidos.',
    option_b: 'Apenas pelo torque do motor.',
    option_c: 'Pela assimetria de peso.',
    option_d: 'Pelo enflechamento das asas.',
    correct_answer: 'a',
    difficulty: 'hard',
    explanation: 'A guinada adversa ocorre porque o aileron que desce produz mais sustentação e, portanto, mais arrasto induzido, puxando o nariz para fora da curva.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Em qual parte do aerofólio ocorre a separação do fluxo de ar durante um estol?',
    option_a: 'Intradorso.',
    option_b: 'Extradorso.',
    option_c: 'No bordo de ataque antes do centro de pressão.',
    option_d: 'Sob o bordo de fuga.',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'A camada limite se descola do extradorso da asa quando o ângulo de ataque é muito grande, destruindo grande parte da sustentação.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Para manter a altitude em uma curva de nível, o piloto deve:',
    option_a: 'Diminuir a potência.',
    option_b: 'Aumentar o ângulo de ataque puxando o manche.',
    option_c: 'Empurrar o manche para frente.',
    option_d: 'Aplicar leme oposto à curva.',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'Na curva, parte da sustentação é usada horizontalmente. Para manter a altitude, a sustentação total precisa aumentar através do aumento do ângulo de ataque.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'A velocidade de planeio de máxima distância (L/D max) ocorre quando:',
    option_a: 'O arrasto parasita é máximo.',
    option_b: 'O arrasto induzido é zero.',
    option_c: 'O arrasto induzido e o arrasto parasita se igualam.',
    option_d: 'A sustentação é o dobro do peso.',
    correct_answer: 'c',
    difficulty: 'hard',
    explanation: 'A eficiência aerodinâmica máxima (menor arrasto total para a sustentação necessária) ocorre no ponto em que o arrasto induzido cruza com o parasita no gráfico.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'A formação de gelo nas asas é perigosa principalmente porque:',
    option_a: 'Aumenta significativamente o peso do avião.',
    option_b: 'Altera o perfil aerodinâmico, diminuindo a sustentação e aumentando o arrasto.',
    option_c: 'Aumenta a eficiência do motor.',
    option_d: 'Faz o CG recuar para trás do limite.',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'Embora o peso aumente, o maior perigo é a deformação do aerofólio, que pode induzir ao estol em velocidades muito mais altas.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Se o tubo de pitot for totalmente bloqueado por gelo (incluindo o dreno), o velocímetro funcionará como um:',
    option_a: 'Altímetro.',
    option_b: 'Variômetro.',
    option_c: 'Indicador de curva.',
    option_d: 'Termômetro.',
    correct_answer: 'a',
    difficulty: 'hard',
    explanation: 'Sem a variação da pressão dinâmica, o velocímetro reagirá apenas à pressão estática, subindo com a altitude e baixando na descida.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Um dos propósitos de se estender os flaps na decolagem é:',
    option_a: 'Aumentar a distância de rolagem.',
    option_b: 'Diminuir o arrasto total a zero.',
    option_c: 'Diminuir a velocidade de decolagem, reduzindo a distância de rolagem.',
    option_d: 'Garantir melhor resfriamento do motor.',
    correct_answer: 'c',
    difficulty: 'easy',
    explanation: 'Flaps de decolagem (normalmente ajustes baixos) aumentam a sustentação, permitindo a rotação com menor velocidade e, assim, pistas mais curtas.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'A tendência da aeronave de guinar para a esquerda devido ao "Efeito de Torque" ocorre porque:',
    option_a: 'Ação e reação; a hélice gira para a direita (em relação ao piloto), causando um giro do eixo longitudinal no sentido oposto.',
    option_b: 'O ar é mais denso no lado esquerdo do motor.',
    option_c: 'As asas têm perfis assimétricos.',
    option_d: 'O leme é deslocado para a direita na fabricação.',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Pela Terceira Lei de Newton (ação e reação), o motor girando a hélice num sentido induz a fuselagem a girar no sentido oposto, aumentando a pressão no trem esquerdo e causando guinada.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Durante o pouso, ao entrar no Efeito Solo, o piloto sentirá a aeronave:',
    option_a: 'Afundar rapidamente.',
    option_b: '"Flutuar", com diminuição acentuada do arrasto induzido.',
    option_c: 'Perder totalmente a eficiência do leme.',
    option_d: 'Estolar de maneira violenta.',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'A proximidade do solo impede o pleno desenvolvimento dos vórtices de ponta de asa, diminuindo o arrasto induzido e causando uma sensação de flutuação.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Para sair de uma atitude inusitada em mergulho com curva acentuada, a primeira ação nos comandos deve ser:',
    option_a: 'Puxar o manche vigorosamente para subir o nariz.',
    option_b: 'Reduzir a potência, nivelar as asas e em seguida levantar suavemente o nariz.',
    option_c: 'Aplicar potência máxima e aplicar leme.',
    option_d: 'Comandar flaps para a posição totalmente abaixada.',
    correct_answer: 'b',
    difficulty: 'hard',
    explanation: 'Puxar num mergulho inclinado aumenta o fator de carga rapidamente; deve-se primeiro tirar potência, nivelar as asas e depois subir o nariz para evitar excesso de carga.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Qual destas forças NÃO atua sobre uma aeronave em planeio perfeito sem motor?',
    option_a: 'Sustentação.',
    option_b: 'Arrasto.',
    option_c: 'Tração.',
    option_d: 'Peso.',
    correct_answer: 'c',
    difficulty: 'easy',
    explanation: 'Em voo planado (sem motor), as forças atuantes são peso, sustentação e arrasto. A tração é zero.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'A velocidade (Vy) representa a velocidade de melhor razão de subida, o que significa que o avião ganhará:',
    option_a: 'Mais altitude em menos distância percorrida no solo.',
    option_b: 'Mais altitude no menor intervalo de tempo.',
    option_c: 'Menos velocidade de planeio.',
    option_d: 'Maior velocidade cruzeiro.',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'Vy maximiza a taxa de subida em pés por minuto.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Quando o ângulo de ataque é aumentado até o limite do estol, o centro de pressão do aerofólio (CG constante):',
    option_a: 'Move-se em direção ao bordo de ataque.',
    option_b: 'Move-se em direção ao bordo de fuga.',
    option_c: 'Permanece imóvel.',
    option_d: 'Move-se para a ponta da asa.',
    correct_answer: 'a',
    difficulty: 'hard',
    explanation: 'Com o aumento do ângulo de ataque em aerofólios assimétricos, o centro de pressão avança para frente até o momento do estol.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O compensador (trim tab) de um leme de direção defletido para a esquerda fará o leme mover-se para a:',
    option_a: 'Esquerda.',
    option_b: 'Direita.',
    option_c: 'Cima.',
    option_d: 'Baixo.',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'O trim tab atua criando uma força aerodinâmica oposta ao movimento desejado, empurrando a superfície de controle para o outro lado.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'A velocidade indicada (IAS) em que ocorre o estol será maior se houver:',
    option_a: 'Diminuição do peso.',
    option_b: 'Voo no efeito solo.',
    option_c: 'Aumento do fator de carga ou peso.',
    option_d: 'Aumento da altitude densidade.',
    correct_answer: 'c',
    difficulty: 'medium',
    explanation: 'Tanto o aumento do peso real quanto o peso aparente (fator de carga) exigem mais sustentação, antecipando o estol para velocidades maiores.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O estol de alta velocidade (estol acelerado) pode ocorrer:',
    option_a: 'Apenas com baixa potência de motor.',
    option_b: 'A qualquer velocidade, dependendo da atitude e aplicação abrupta dos comandos.',
    option_c: 'Somente se os flaps estiverem estendidos.',
    option_d: 'Em velocidade muito inferior à VS0.',
    correct_answer: 'b',
    difficulty: 'hard',
    explanation: 'Estóis dependem do ângulo de ataque crítico, que pode ser atingido a altas velocidades se houver mudança brusca de trajetória.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Um avião estável direcionamente tenderá a retornar à proa original caso sofra uma perturbação causada por:',
    option_a: 'Turbulência.',
    option_b: 'Ailerons.',
    option_c: 'Arrasto induzido.',
    option_d: 'Profundores.',
    correct_answer: 'a',
    difficulty: 'easy',
    explanation: 'Estabilidade direcional (eixo vertical) é a capacidade de recuperar a proa após ser perturbada pelo vento/turbulência.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Qual dispositivo nas asas tem a função primária de diminuir o fluxo transversal do ar em perfis de alta velocidade, reduzindo o estol de ponta?',
    option_a: 'Vortex generators.',
    option_b: 'Fences (Cercas aerodinâmicas).',
    option_c: 'Flaps fowler.',
    option_d: 'Spoilers.',
    correct_answer: 'b',
    difficulty: 'hard',
    explanation: 'As cercas (fences) limitam o fluxo de ar ao longo da envergadura em asas enflechadas, retardando o estol de ponta.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'A diferença geométrica entre a raiz e a ponta de uma asa em relação à torção é feita para que:',
    option_a: 'A ponta estole primeiro que a raiz.',
    option_b: 'A raiz estole primeiro, mantendo controle de aileron.',
    option_c: 'Reduza o peso total da asa.',
    option_d: 'Aumente o arrasto de forma.',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'A torção geométrica garante que a raiz tenha maior ângulo de incidência, estolando antes e preservando o fluxo de ar nos ailerons, mantendo controle lateral.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'A esteira de turbulência gerada por uma aeronave voando tem maior intensidade quando ela é:',
    option_a: 'Pesada, limpa e rápida.',
    option_b: 'Leve, suja e lenta.',
    option_c: 'Pesada, limpa e lenta.',
    option_d: 'Leve, suja e rápida.',
    correct_answer: 'c',
    difficulty: 'medium',
    explanation: 'Os vórtices mais intensos ocorrem com o avião pesado (maior sustentação), limpo (sem flaps) e lento (alto ângulo de ataque).'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Para evitar a esteira de turbulência ao decolar atrás de um avião de grande porte, o piloto deve decolar:',
    option_a: 'Antes do ponto de rotação da aeronave precedente e manter-se acima de sua trajetória de subida.',
    option_b: 'Depois do ponto de rotação e abaixo de sua trajetória.',
    option_c: 'No mesmo ponto de rotação e seguir à direita.',
    option_d: 'Ignorando a rotação, já que a esteira vai para cima.',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Vórtices descem e se formam na rotação. Decolando antes e ficando acima evita as áreas de turbulência.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O que representa o VNE no arco de velocidades de um velocímetro analógico?',
    option_a: 'Velocidade nunca exceder, representada pela linha vermelha.',
    option_b: 'Velocidade máxima com flap estendido, arco branco.',
    option_c: 'Velocidade normal de cruzeiro, arco verde.',
    option_d: 'Velocidade de aproximação.',
    correct_answer: 'a',
    difficulty: 'easy',
    explanation: 'VNE (Velocity Never Exceed) é a velocidade limite estrutural, a linha vermelha.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O arco amarelo no velocímetro indica a faixa de operação:',
    option_a: 'Proibida para todos os voos.',
    option_b: 'Permitida apenas em ar calmo (faixa de cautela).',
    option_c: 'Exclusiva para uso de flaps.',
    option_d: 'Para velocidades mínimas de decolagem.',
    correct_answer: 'b',
    difficulty: 'easy',
    explanation: 'O arco amarelo é a faixa de cautela e só deve ser utilizado quando o ar estiver isento de turbulência forte.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Qual das atitudes de voo aumenta severamente o consumo de combustível sem ganho de elevação significativa?',
    option_a: 'Cruzeiro normal.',
    option_b: 'Voo lento na parte posterior da curva de potência (region of reversed command).',
    option_c: 'Descida ociosa.',
    option_d: 'Planeio.',
    correct_answer: 'b',
    difficulty: 'hard',
    explanation: 'Na região de comando reverso, para manter uma atitude mais lenta, requer-se *mais* potência devido ao aumento dramático do arrasto induzido.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Uma hélice de passo fixo alcança sua máxima eficiência:',
    option_a: 'Em qualquer condição de voo.',
    option_b: 'Somente na velocidade de cruzeiro projetada pelo fabricante.',
    option_c: 'No pouso e decolagem.',
    option_d: 'Apenas em grandes altitudes.',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'O passo fixo é um compromisso; ele atinge o melhor desempenho de avanço e eficiência somente em uma dada velocidade de voo e RPM para o qual foi projetado.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O avanço real de uma hélice a cada revolução chama-se avanço efetivo. A diferença entre o avanço geométrico (teórico) e o efetivo chama-se:',
    option_a: 'Tração.',
    option_b: 'Passo útil.',
    option_c: 'Recuo da hélice (Slip).',
    option_d: 'Ângulo de pá.',
    correct_answer: 'c',
    difficulty: 'medium',
    explanation: 'O slip ou recuo é a perda de avanço causada por "escorregamento" do ar através das pás da hélice em movimento.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Um avião submetido a fator de carga negativo no voo invertido suporta mais carga estrutural se projetado para a categoria:',
    option_a: 'Normal.',
    option_b: 'Utilitária.',
    option_c: 'Acrobática.',
    option_d: 'Comercial.',
    correct_answer: 'c',
    difficulty: 'easy',
    explanation: 'A categoria acrobática é projetada para suportar fatores de carga negativos até pelo menos -3.0 Gs.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Em uma decolagem com vento de través da esquerda, os ailerons devem ser inicialmente aplicados:',
    option_a: 'Totalmente para a direita.',
    option_b: 'Neutros.',
    option_c: 'Totalmente para a esquerda.',
    option_d: 'Opostos ao leme.',
    correct_answer: 'c',
    difficulty: 'medium',
    explanation: 'Aplicar ailerons "contra o vento" evita que a asa seja levantada pela força do vento, mantendo controle direcional na rolagem.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'As superfícies auxiliares que podem ser abertas na parte superior da asa para destruir a sustentação no pouso são chamadas de:',
    option_a: 'Compensadores.',
    option_b: 'Slats.',
    option_c: 'Flaps.',
    option_d: 'Spoilers.',
    correct_answer: 'd',
    difficulty: 'easy',
    explanation: 'Spoilers são placas que sobem do extradorso da asa para perturbar o fluxo de ar e reduzir rapidamente a sustentação.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Ao recolher o trem de pouso após a decolagem, a aeronave tem inicialmente uma melhora de desempenho devido à diminuição do arrasto:',
    option_a: 'Parasita.',
    option_b: 'Induzido.',
    option_c: 'Por compressibilidade.',
    option_d: 'Interno.',
    correct_answer: 'a',
    difficulty: 'easy',
    explanation: 'O trem de pouso contribui fortemente para o arrasto parasita; ao guardá-lo, o arrasto diminui consideravelmente.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Na glissada frontal (forward slip), muito utilizada para perder altitude rapidamente antes do pouso sem ganhar velocidade, cruza-se os comandos de:',
    option_a: 'Profundor e aileron.',
    option_b: 'Aileron e leme de direção.',
    option_c: 'Leme de direção e flaps.',
    option_d: 'Acelerador e leme.',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'A glissada intencional envolve inclinar o avião com aileron e aplicar o leme de direção no sentido oposto para evitar a curva.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Aerofólios simétricos (corda divide o perfil igualmente) não produzem sustentação quando seu ângulo de ataque é:',
    option_a: '15 graus.',
    option_b: '10 graus.',
    option_c: 'Zero grau.',
    option_d: 'Negativo.',
    correct_answer: 'c',
    difficulty: 'easy',
    explanation: 'No perfil simétrico com ângulo zero, a passagem do ar é igual em cima e embaixo, gerando zero sustentação.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'A inclinação longitudinal da hélice em relação ao eixo horizontal de giro (para frente) é chamada de:',
    option_a: 'Passo.',
    option_b: 'Torção.',
    option_c: 'Rake.',
    option_d: 'Track.',
    correct_answer: 'c',
    difficulty: 'hard',
    explanation: 'O rake ou flechamento pode ser empregado no design da pá da hélice (não confundir com passo ou torção).'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O fenômeno conhecido como "Shimmy" afeta qual componente da aeronave?',
    option_a: 'Profundor, causando oscilação em alta velocidade.',
    option_b: 'A roda do trem de pouso do nariz, causando vibrações laterais.',
    option_c: 'As asas, durante forte turbulência.',
    option_d: 'A hélice fora de balanceamento.',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'Shimmy é a oscilação violenta do trem de pouso direcional que geralmente exige amortecedores para ser evitado.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Ao alterar-se o ângulo de incidência do estabilizador horizontal inteiro, estamos usando um dispositivo conhecido como:',
    option_a: 'Stabilator ou profundor compensável.',
    option_b: 'Elevon.',
    option_c: 'Flaperon.',
    option_d: 'Spoileron.',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'O stabilator (estabilizador inteiro móvel) substitui o profundor convencional na alteração de arfagem.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Vento de cauda durante a aproximação final causará:',
    option_a: 'Aumento na razão de descida para manter o trajeto de aproximação.',
    option_b: 'Redução da velocidade de estol.',
    option_c: 'Diminuição da distância de rolagem.',
    option_d: 'Aumento dramático de sustentação.',
    correct_answer: 'a',
    difficulty: 'hard',
    explanation: 'O vento de cauda eleva a velocidade no solo (ground speed), forçando o piloto a descer mais rápido para não ultrapassar o ponto de toque.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O Efeito Solo é mais perceptível a qual distância do solo?',
    option_a: 'Altura de duas envergaduras.',
    option_b: 'Altura inferior à metade ou até a medida da envergadura da aeronave.',
    option_c: '1000 pés AGL.',
    option_d: 'Independe da distância desde que o trem esteja baixo.',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'Geralmente as alterações aerodinâmicas do Efeito Solo se iniciam a partir de 1 envergadura de altura, sendo extremas mais perto do chão.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Uma aeronave atinge a sua teto absoluto (absolute ceiling) quando:',
    option_a: 'A razão máxima de subida for 100 ft/min.',
    option_b: 'A razão máxima de subida for 0 ft/min.',
    option_c: 'A velocidade de estol for zero.',
    option_d: 'Houver pressão negativa na cabine.',
    correct_answer: 'b',
    difficulty: 'easy',
    explanation: 'Teto absoluto é onde o avião perde a capacidade de continuar subindo (razão 0 ft/min).'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Qual dispositivo fornece tanto o controle de inclinação quanto de arfagem em aeronaves de asa em delta?',
    option_a: 'Elevons.',
    option_b: 'Flaperons.',
    option_c: 'Ruddervators.',
    option_d: 'Trim tabs.',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Elevons combinam a função de profundor (elevators) e ailerons em uma única superfície na borda de fuga.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Para converter a pressão dinâmica em indicação de velocidade, o tubo de Pitot é conectado diretamente ao:',
    option_a: 'Altímetro.',
    option_b: 'Velocímetro.',
    option_c: 'Climb.',
    option_d: 'Machímetro de estol.',
    correct_answer: 'b',
    difficulty: 'easy',
    explanation: 'O tubo de Pitot envia pressão total (dinâmica+estática) para o velocímetro, que mede a diferença com a pressão estática.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O aumento da Altitude Densidade terá qual efeito na decolagem de uma aeronave leve com motor aspirado?',
    option_a: 'Diminuição do arrasto, facilitando a decolagem.',
    option_b: 'Aumento da sustentação e menor distância de corrida.',
    option_c: 'Diminuição da potência do motor, da eficiência da hélice e aumento da corrida de decolagem.',
    option_d: 'Nenhuma alteração em motores a pistão.',
    correct_answer: 'c',
    difficulty: 'medium',
    explanation: 'Ar menos denso prejudica a combustão, reduz a tração da hélice e exige mais velocidade de solo para gerar sustentação, alongando a pista.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Num avião voando de costas (invertido), qual estrutura fornece sustentação positiva para manter o voo nivelado?',
    option_a: 'Aileron invertido.',
    option_b: 'Extradorso funcionando como intradorso, mediante ângulo de ataque fortemente negativo em relação à corda.',
    option_c: 'A hélice criando força vetorial.',
    option_d: 'A asa para de gerar sustentação e o avião flutua pela gravidade.',
    correct_answer: 'b',
    difficulty: 'hard',
    explanation: 'O piloto empurra o manche para criar ângulo de ataque suficiente no aerofólio (agora de cabeça para baixo) para gerar sustentação para "cima" (relativo ao céu).'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O que o "Dutch Roll" (rolamento holandês) representa em relação à estabilidade da aeronave?',
    option_a: 'Um avião com forte estabilidade direcional e fraca estabilidade lateral.',
    option_b: 'Um avião com forte estabilidade lateral e fraca estabilidade direcional.',
    option_c: 'Um avião impossível de ser controlado manualmente.',
    option_d: 'Estabilidade longitudinal negativa.',
    correct_answer: 'b',
    difficulty: 'hard',
    explanation: 'Quando as asas tendem a nivelar-se rápido demais (muita est. lateral), mas o nariz vaga de lado a lado por falta de est. direcional adequada.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Uma hélice que pode ter seu ângulo da pá ajustado automaticamente para manter RPM constante é uma hélice:',
    option_a: 'De passo fixo.',
    option_b: 'De passo ajustável no solo.',
    option_c: 'De velocidade constante (constant-speed).',
    option_d: 'Reversível.',
    correct_answer: 'c',
    difficulty: 'easy',
    explanation: 'Através de um governador, o passo é modificado para manter a rotação desejada independente de mudanças de potência e atitude.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'As pás do cone da hélice possuem ângulo de pá maior:',
    option_a: 'Na ponta.',
    option_b: 'No meio do comprimento.',
    option_c: 'Próximo ao cubo ou raiz.',
    option_d: 'No bordo de ataque.',
    correct_answer: 'c',
    difficulty: 'medium',
    explanation: 'Como a raiz gira mais devagar (menor distância percorrida por giro) do que a ponta, ela tem ângulo de pá maior para ter tração mais uniforme em toda a pá.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Para realizar uma curva, as duas forças principais combinadas que formam o fator de carga são a sustentação e:',
    option_a: 'O peso.',
    option_b: 'A força centrífuga.',
    option_c: 'O arrasto.',
    option_d: 'A tração.',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'Durante a curva, a força centrífuga atua na direção de fora do raio da curva combinada com a força gravitacional; o fator de carga suporta a resultante (força G).'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Em qual situação é prudente usar a "Velocity de Manobra (Va)"?',
    option_a: 'Voo noturno sob névoa.',
    option_b: 'Ao encontrar forte turbulência para prevenir dano estrutural.',
    option_c: 'Sempre que o trem de pouso for baixado.',
    option_d: 'Na subida em voo por instrumentos.',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'A velocidade de manobra é a velocidade acima da qual a deflexão total dos comandos pode quebrar a aeronave antes do estol. Na turbulência severa é o limite seguro.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'A velocidade VA de manobra geralmente varia de acordo com:',
    option_a: 'O peso da aeronave.',
    option_b: 'A altitude densidade.',
    option_c: 'O centro de gravidade.',
    option_d: 'A temperatura exterior.',
    correct_answer: 'a',
    difficulty: 'hard',
    explanation: 'Quando o avião está mais leve, a VA diminui; se está com peso máximo, a VA é maior. Aviões mais leves estolam com maior facilidade perante comandos bruscos.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Qual destas ações agrava o arrasto induzido em um avião?',
    option_a: 'Voar em velocidade elevada de cruzeiro.',
    option_b: 'Manter voo lento, exigindo alto ângulo de ataque.',
    option_c: 'Limpar a aeronave e retirar antenas sobressalentes.',
    option_d: 'Retrair os flaps na subida.',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'O arrasto induzido aumenta severamente quanto menor a velocidade, pois exige alto ângulo de ataque, criando vórtices maiores.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Numa reta nivelada com potência reduzida bruscamente, o torque remanescente tenderá a fazer o avião:',
    option_a: 'Cabrar e guinar pra esquerda.',
    option_b: 'Picar e tender a guinar para a direita.',
    option_c: 'Realizar um parafuso plano.',
    option_d: 'Não apresenta reação imediata.',
    correct_answer: 'b',
    difficulty: 'hard',
    explanation: 'Ao tirar potência, tira-se sustentação do profundor gerada pela esteira da hélice (nariz cai) e cessa a guinada à esquerda (indo de encontro ao lado oposto, para a direita).'
  }
];
