export const part1 = [
  {
    bloco_id: 'teoria_de_voo',
    text: 'De acordo com o Princípio de Bernoulli, o que ocorre com a pressão de um fluido quando sua velocidade aumenta?',
    option_a: 'A pressão aumenta proporcionalmente à velocidade',
    option_b: 'A pressão diminui quando a velocidade aumenta',
    option_c: 'A pressão permanece constante independentemente da velocidade',
    option_d: 'A pressão dobra quando a velocidade dobra',
    correct_answer: 'b',
    difficulty: 'easy',
    explanation: 'O Princípio de Bernoulli afirma que em um fluxo de fluido, quando a velocidade aumenta, a pressão estática diminui. Isso é fundamental para explicar a geração de sustentação nas asas.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Qual das forças atua perpendicularmente à trajetória de voo e se opõe à gravidade em voo nivelado?',
    option_a: 'Arrasto',
    option_b: 'Tração',
    option_c: 'Sustentação',
    option_d: 'Peso',
    correct_answer: 'c',
    difficulty: 'easy',
    explanation: 'A sustentação atua perpendicularmente à trajetória de voo e, em voo nivelado, equilibra o peso da aeronave.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Em voo nivelado e em velocidade constante, qual é a relação entre as quatro forças que atuam na aeronave?',
    option_a: 'Sustentação > Peso e Tração > Arrasto',
    option_b: 'Sustentação = Peso e Tração = Arrasto',
    option_c: 'Sustentação < Peso e Tração < Arrasto',
    option_d: 'Sustentação = Arrasto e Tração = Peso',
    correct_answer: 'b',
    difficulty: 'easy',
    explanation: 'Em voo nivelado e velocidade constante, a aeronave está em equilíbrio: a sustentação iguala o peso e a tração iguala o arrasto.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O ângulo de ataque é definido como o ângulo entre:',
    option_a: 'A linha da corda do perfil alar e o horizonte',
    option_b: 'A linha da corda do perfil alar e a direção do vento relativo',
    option_c: 'A asa e a fuselagem da aeronave',
    option_d: 'O eixo longitudinal da aeronave e o horizonte',
    correct_answer: 'b',
    difficulty: 'easy',
    explanation: 'O ângulo de ataque é o ângulo formado entre a linha da corda do perfil alar e a direção do vento relativo (trajetória do ar que incide na asa).'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O que é a linha de corda de um perfil alar?',
    option_a: 'A linha que une o ponto de maior espessura ao bordo de fuga',
    option_b: 'A linha imaginária reta que une o bordo de ataque ao bordo de fuga',
    option_c: 'A linha curva que representa a curvatura média do perfil',
    option_d: 'A linha que divide o perfil em partes superior e inferior iguais',
    correct_answer: 'b',
    difficulty: 'easy',
    explanation: 'A linha de corda é a linha imaginária reta que une o bordo de ataque (ponto mais à frente) ao bordo de fuga (ponto mais atrás) do perfil alar.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O que é envergadura de uma asa?',
    option_a: 'A distância do bordo de ataque ao bordo de fuga',
    option_b: 'A espessura máxima do perfil alar',
    option_c: 'A distância de uma ponta à outra da asa',
    option_d: 'A área total da superfície alar',
    correct_answer: 'c',
    difficulty: 'easy',
    explanation: 'Envergadura é a dimensão da asa medida de ponta a ponta, ou seja, a distância total de uma extremidade à outra da asa.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O que acontece com a sustentação quando o ângulo de ataque aumenta progressivamente até o ângulo crítico?',
    option_a: 'A sustentação diminui constantemente',
    option_b: 'A sustentação permanece constante',
    option_c: 'A sustentação aumenta até o ângulo crítico e depois cai abruptamente',
    option_d: 'A sustentação aumenta indefinidamente',
    correct_answer: 'c',
    difficulty: 'easy',
    explanation: 'Com o aumento do ângulo de ataque, a sustentação cresce até atingir o ângulo crítico (ângulo de estol). Além desse ponto, ocorre separação do fluxo de ar e a sustentação cai bruscamente.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O estol ocorre quando:',
    option_a: 'A velocidade da aeronave cai abaixo de um valor mínimo absoluto',
    option_b: 'O ângulo de ataque excede o ângulo crítico, causando separação do fluxo',
    option_c: 'O motor para de funcionar em voo',
    option_d: 'A tração supera o arrasto',
    correct_answer: 'b',
    difficulty: 'easy',
    explanation: 'O estol é causado pelo excesso de ângulo de ataque além do ângulo crítico, provocando separação do fluxo de ar na extradorso da asa e perda brusca de sustentação. Não é necessariamente uma questão de velocidade baixa.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Qual é o procedimento correto de recuperação de um estol?',
    option_a: 'Puxar o manche para aumentar o ângulo de ataque e aplicar plena potência',
    option_b: 'Baixar o nariz para reduzir o ângulo de ataque, aplicar potência e nivelar as asas',
    option_c: 'Aplicar pedal de leme oposto à queda da asa e manter a altitude',
    option_d: 'Retrair os flapes imediatamente e aumentar a velocidade',
    correct_answer: 'b',
    difficulty: 'easy',
    explanation: 'Para recuperar do estol, deve-se reduzir o ângulo de ataque empurrando o manche (baixando o nariz), aplicar potência para ganhar energia e nivelar as asas com os ailerons.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'A 3ª Lei de Newton aplicada à geração de sustentação estabelece que:',
    option_a: 'Para cada ação há uma reação de mesma intensidade e direção',
    option_b: 'A asa deflete o ar para baixo, e a reação é uma força para cima (sustentação)',
    option_c: 'A força de sustentação é proporcional à massa da aeronave',
    option_d: 'O ar em repouso não exerce força sobre a asa',
    correct_answer: 'b',
    difficulty: 'easy',
    explanation: 'Pela 3ª Lei de Newton, ao defletir o ar para baixo, a asa recebe uma força de reação igual e oposta, direcionada para cima — a sustentação.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O que é o bordo de ataque de um perfil alar?',
    option_a: 'A parte mais fina e afilada da parte traseira da asa',
    option_b: 'A parte frontal arredondada da asa que enfrenta o fluxo de ar',
    option_c: 'A superfície superior (extradorso) da asa',
    option_d: 'A região de maior espessura do perfil',
    correct_answer: 'b',
    difficulty: 'easy',
    explanation: 'O bordo de ataque é a parte dianteira do perfil alar, geralmente arredondada, que divide o fluxo de ar entre a superfície superior e inferior da asa.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Em voo em curva coordenada, a sustentação necessária comparada ao voo nivelado é:',
    option_a: 'Menor, pois parte da sustentação é usada para girar',
    option_b: 'Igual, pois a curva não altera o peso',
    option_c: 'Maior, pois a componente vertical deve ainda equilibrar o peso total',
    option_d: 'Nula na direção vertical durante a curva',
    correct_answer: 'c',
    difficulty: 'medium',
    explanation: 'Em curva, a sustentação total deve ser maior porque apenas sua componente vertical equilibra o peso. A componente horizontal fornece a força centrípeta para a curva.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O fator de carga (n) em voo nivelado é:',
    option_a: '0',
    option_b: '0,5',
    option_c: '1',
    option_d: '2',
    correct_answer: 'c',
    difficulty: 'easy',
    explanation: 'Em voo nivelado e constante, o fator de carga é igual a 1 (n=1), pois a sustentação iguala exatamente o peso da aeronave.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Qual é o fator de carga em uma curva coordenada com inclinação de 60°?',
    option_a: '1,0',
    option_b: '1,41',
    option_c: '1,73',
    option_d: '2,0',
    correct_answer: 'd',
    difficulty: 'medium',
    explanation: 'O fator de carga em curva é n = 1/cos(ângulo de inclinação). Para 60°: n = 1/cos(60°) = 1/0,5 = 2,0.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'A velocidade de estol varia com o fator de carga pela fórmula:',
    option_a: 'Vs_n = Vs × n',
    option_b: 'Vs_n = Vs × √n',
    option_c: 'Vs_n = Vs / √n',
    option_d: 'Vs_n = Vs × n²',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'A velocidade de estol com fator de carga é Vs_n = Vs × √n. Com fator de carga aumentado (curvas, turbulência), a velocidade de estol aumenta.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Em uma curva com fator de carga igual a 4, a velocidade de estol em relação ao voo nivelado é:',
    option_a: 'A mesma',
    option_b: 'O dobro',
    option_c: 'Quatro vezes maior',
    option_d: '√4 = 2 vezes maior',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'Vs_n = Vs × √4 = Vs × 2. Portanto, a velocidade de estol dobra quando o fator de carga é 4.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O que é razão de planeio?',
    option_a: 'A velocidade vertical de descida em metros por segundo',
    option_b: 'A relação entre a distância horizontal percorrida e a altitude perdida',
    option_c: 'O ângulo formado entre a trajetória e o horizonte durante a descida',
    option_d: 'A velocidade de aproximação no pouso',
    correct_answer: 'b',
    difficulty: 'easy',
    explanation: 'A razão de planeio (L/D ou planar ratio) é a distância horizontal percorrida para cada unidade de altitude perdida. Por exemplo, razão 10:1 significa 10 km horizontais para cada 1 km de altitude perdida.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'A melhor razão de planeio é obtida na velocidade correspondente à:',
    option_a: 'Máxima sustentação (CL máximo)',
    option_b: 'Máxima relação sustentação/arrasto (CL/CD máximo)',
    option_c: 'Mínima velocidade possível (Vs)',
    option_d: 'Máxima velocidade operacional (Vno)',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'A melhor razão de planeio ocorre na velocidade onde a relação L/D (sustentação/arrasto) é máxima, correspondendo ao ponto de mínimo arrasto total na curva polar.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Vx é definida como:',
    option_a: 'A velocidade de melhor razão de subida (maior altitude por tempo)',
    option_b: 'A velocidade de maior ganho de altitude por distância percorrida horizontalmente',
    option_c: 'A velocidade de cruzeiro mais econômica',
    option_d: 'A velocidade de estol com flapes recolhidos',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'Vx é a velocidade de melhor ângulo de subida, que maximiza o ganho de altitude por distância horizontal. É usada para superar obstáculos próximos ao ponto de decolagem.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Vy é definida como:',
    option_a: 'A velocidade de melhor ângulo de subida',
    option_b: 'A velocidade de maior razão de subida (maior altitude por unidade de tempo)',
    option_c: 'A velocidade de cruzeiro normal',
    option_d: 'A velocidade máxima com flapes estendidos',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'Vy é a velocidade de melhor razão de subida, que maximiza o ganho de altitude por unidade de tempo (pés/min ou m/min). É usada para atingir a altitude de cruzeiro mais rapidamente.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Vne é:',
    option_a: 'A velocidade de nevoa (operação em IMC)',
    option_b: 'A velocidade nunca a exceder (Never Exceed Speed)',
    option_c: 'A velocidade normal de cruzeiro',
    option_d: 'A velocidade de estol normal',
    correct_answer: 'b',
    difficulty: 'easy',
    explanation: 'Vne (Never Exceed Speed) é a velocidade máxima absoluta da aeronave. Excedê-la pode causar danos estruturais ou perda de controle. É indicada no velocímetro pela linha vermelha.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Vno é:',
    option_a: 'A velocidade máxima de operação normal (arco verde do velocímetro)',
    option_b: 'A velocidade de pouso normal',
    option_c: 'A velocidade mínima de controle',
    option_d: 'A velocidade nunca a exceder',
    correct_answer: 'a',
    difficulty: 'easy',
    explanation: 'Vno é a velocidade máxima de operação estrutural, o limite superior do arco verde do velocímetro. Acima dela, só se pode voar em condições de ar calmo.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Va é a velocidade de manobra. Voar abaixo de Va garante que:',
    option_a: 'A aeronave não pode estolar',
    option_b: 'A aeronave estolará antes de sofrer dano estrutural com deflexão total dos controles',
    option_c: 'A aeronave pode suportar qualquer turbulência sem danos',
    option_d: 'Os flapes podem ser estendidos com segurança',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'Va é a velocidade de manobra: abaixo dela, com deflexão total dos controles, a aeronave entrará em estol antes de sofrer danos estruturais, protegendo a estrutura.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Vs0 é:',
    option_a: 'A velocidade de estol em configuração limpa (flapes recolhidos)',
    option_b: 'A velocidade de estol em configuração de pouso (flapes estendidos)',
    option_c: 'A velocidade zero de sustentação',
    option_d: 'A velocidade de subida máxima',
    correct_answer: 'b',
    difficulty: 'easy',
    explanation: 'Vs0 é a velocidade de estol em configuração de pouso, com flapes totalmente estendidos e trem de pouso abaixado. É o limite inferior do arco branco do velocímetro.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Vfe é:',
    option_a: 'A velocidade de voo em formação',
    option_b: 'A velocidade máxima com os flapes estendidos',
    option_c: 'A velocidade final de aproximação',
    option_d: 'A velocidade mínima de cruzeiro econômico',
    correct_answer: 'b',
    difficulty: 'easy',
    explanation: 'Vfe (Flap Extended Speed) é a velocidade máxima com que os flapes podem ser estendidos sem causar danos estruturais. É o limite superior do arco branco do velocímetro.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Qual é o efeito principal da extensão dos flapes na sustentação e no arrasto?',
    option_a: 'Aumenta a sustentação e diminui o arrasto',
    option_b: 'Aumenta a sustentação e aumenta o arrasto',
    option_c: 'Diminui a sustentação e aumenta o arrasto',
    option_d: 'Não altera a sustentação, apenas aumenta o arrasto',
    correct_answer: 'b',
    difficulty: 'easy',
    explanation: 'Os flapes aumentam a curvatura do perfil, elevando a sustentação a baixas velocidades, mas também aumentam significativamente o arrasto.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Os slats são dispositivos de hipersustentação instalados:',
    option_a: 'No bordo de fuga da asa, atrás dos ailerons',
    option_b: 'No bordo de ataque da asa',
    option_c: 'Na parte superior da fuselagem',
    option_d: 'Na cauda da aeronave',
    correct_answer: 'b',
    difficulty: 'easy',
    explanation: 'Os slats são superfícies móveis instaladas no bordo de ataque da asa. Quando estendidos, aumentam a curvatura e permitem maiores ângulos de ataque sem estol, aumentando a sustentação a baixas velocidades.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Os spoilers têm como função principal:',
    option_a: 'Aumentar a sustentação durante a decolagem',
    option_b: 'Reduzir a sustentação e aumentar o arrasto para desacelerar ou desfazer sustentação',
    option_c: 'Melhorar a estabilidade longitudinal',
    option_d: 'Substituir os ailerons em baixas velocidades',
    correct_answer: 'b',
    difficulty: 'easy',
    explanation: 'Os spoilers (destruidores de sustentação) são painéis que se elevam da superfície da asa para interromper o fluxo laminar, reduzindo a sustentação e aumentando o arrasto. São usados no pouso e para controle de rolagem em algumas aeronaves.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O efeito solo ocorre quando a aeronave está voando próxima ao solo. Qual é seu principal efeito aerodinâmico?',
    option_a: 'Aumento do arrasto induzido e redução da sustentação',
    option_b: 'Redução do arrasto induzido e aumento da eficiência aerodinâmica',
    option_c: 'Aumento da velocidade de estol da aeronave',
    option_d: 'Redução da potência efetiva do motor',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'O efeito solo reduz o arrasto induzido ao restringir os vórtices de ponta de asa, aumentando a eficiência aerodinâmica. A aeronave "flutua" mais facilmente próxima ao solo.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O torque de reação do motor em aeronaves com hélice sentido horário (visto de atrás) tende a:',
    option_a: 'Rolar a aeronave para a direita',
    option_b: 'Rolar a aeronave para a esquerda',
    option_c: 'Cabrar a aeronave',
    option_d: 'Guinhar a aeronave para a direita',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'Pela 3ª Lei de Newton, se a hélice gira no sentido horário (visto de trás), a reação tende a rolar a aeronave no sentido anti-horário, ou seja, para a esquerda.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O P-factor (fator assimétrico de tração) é mais pronunciado quando:',
    option_a: 'A aeronave voa em velocidade de cruzeiro em voo nivelado',
    option_b: 'A aeronave está em alto ângulo de ataque (subida íngreme ou baixa velocidade)',
    option_c: 'O motor opera em baixa potência na descida',
    option_d: 'A aeronave voa em condições de zero ângulo de ataque',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'O P-factor ocorre quando a aeronave está em alto ângulo de ataque. Nessa situação, a pá descendente da hélice tem ângulo de ataque maior que a pá ascendente, gerando mais tração do lado direito e guinhando a aeronave para a esquerda (hélice horária).'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O efeito giroscópico da hélice em rotação afeta a aeronave quando:',
    option_a: 'Há variação de potência do motor',
    option_b: 'Há mudança de atitude da aeronave (precessão giroscópica)',
    option_c: 'A aeronave excede a velocidade Vne',
    option_d: 'Os flapes são estendidos',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'A hélice em rotação age como um giroscópio. Quando a aeronave muda de atitude (ex: levantamento do nariz no decolar), ocorre precessão giroscópica que gera forças em eixos perpendiculares ao movimento aplicado.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'A corredeira (slipstream) do motor a hélice afeta principalmente:',
    option_a: 'A temperatura do motor durante o voo',
    option_b: 'O leme de direção e a cauda, causando tendência de guinada',
    option_c: 'A eficiência dos flapes em baixas velocidades',
    option_d: 'A estabilidade longitudinal da aeronave em cruzeiro',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'A corredeira (fluxo helicoidal do ar acelerado pela hélice) impacta a deriva vertical e a cauda com uma força lateral, causando tendência de guinada, geralmente para a esquerda em aeronaves com hélice horária.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O que é a espiral descendente (graveyard spiral)?',
    option_a: 'Um tipo de estol em curva acentuada',
    option_b: 'Uma descida em espiral com inclinação crescente onde a aeronave ganha velocidade e altitude é rapidamente perdida',
    option_c: 'Um procedimento de aproximação por instrumentos',
    option_d: 'Uma manobra acrobática controlada',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'A espiral descendente (graveyard spiral) é uma situação perigosa em IMC: a aeronave entra em curva, o piloto sem referências externas puxa o manche (aumentando fator de carga), aumenta a velocidade e a taxa de descida, podendo levar à desintegração estrutural.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O flutter aerodinâmico é:',
    option_a: 'Uma oscilação controlada usada para testar a estrutura da asa',
    option_b: 'Uma oscilação aeroelástica instável que pode levar à falha estrutural se não corrigida',
    option_c: 'O batimento normal dos ailerons em turbulência leve',
    option_d: 'A vibração natural do motor em baixa rotação',
    correct_answer: 'b',
    difficulty: 'hard',
    explanation: 'Flutter é uma oscilação aeroelástica acoplada (vibração estrutural + forças aerodinâmicas) que pode tornar-se divergente e causar falha catastrófica da estrutura. É por isso que existe a limitação de Vne.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Divergência aerodinâmica em uma asa ocorre quando:',
    option_a: 'A asa torce sob carga aerodinâmica de forma que as forças aerodinâmicas aumentam ainda mais a torção',
    option_b: 'O fluxo de ar se separa prematuramente do bordo de ataque',
    option_c: 'Os dois lados da asa geram sustentações diferentes',
    option_d: 'A asa vibra com frequência crescente até o estol',
    correct_answer: 'a',
    difficulty: 'hard',
    explanation: 'Divergência é uma instabilidade aeroelástica estática: a carga aerodinâmica torce a asa, aumentando o ângulo de ataque, o que aumenta a sustentação e a torção ainda mais, num ciclo que pode levar à falha estrutural.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O reverso de comando (control reversal) em ailerons ocorre quando:',
    option_a: 'O piloto aplica aileron errado durante a recuperação do estol',
    option_b: 'A velocidade é tão alta que a deflexão do aileron torce a asa e produz rolamento oposto ao desejado',
    option_c: 'Os ailerons estão invertidos por erro de manutenção',
    option_d: 'O fluxo de ar se inverte ao redor do perfil alar',
    correct_answer: 'b',
    difficulty: 'hard',
    explanation: 'O reverso de comando ocorre em velocidades muito elevadas: a força aerodinâmica sobre o aileron defletido torce a asa de modo que o efeito de rolamento é oposto ao comandado pelo piloto.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Em uma curva coordenada, o slip indicator (bola) deve estar:',
    option_a: 'Deslocada para o lado externo da curva',
    option_b: 'Deslocada para o lado interno da curva',
    option_c: 'Centralizada',
    option_d: 'Na posição depende da velocidade da curva',
    correct_answer: 'c',
    difficulty: 'easy',
    explanation: 'Em curva coordenada, as forças laterais são equilibradas e o slip indicator (bola) permanece centralizado. Bola deslocada indica curva descoordinada (derrapagem ou deslizamento).'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Se a bola do slip indicator está deslocada para a esquerda durante uma curva à esquerda, a aeronave está em:',
    option_a: 'Curva coordenada',
    option_b: 'Derrapagem (skid) — excesso de pedal interno',
    option_c: 'Deslizamento (slip) — falta de pedal interno ou excesso de inclinação',
    option_d: 'Estol em curva',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'Bola deslocada para o lado interno da curva (esquerda numa curva à esquerda) indica derrapagem (skid): a cauda está deslizando para fora por excesso de pedal ou insuficiente inclinação.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O efeito adverso do aileron refere-se a:',
    option_a: 'A tendência de o aileron travar em deflexões máximas',
    option_b: 'A guinada momentânea na direção oposta à rolagem iniciada',
    option_c: 'A perda de eficiência dos ailerons em alta velocidade',
    option_d: 'O aumento excessivo de sustentação com aileron baixado',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'O efeito adverso do aileron ocorre porque o aileron abaixado gera mais arrasto induzido do que o levantado, causando uma guinada momentânea para o lado do aileron abaixado (oposto à rolagem desejada).'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'A estabilidade longitudinal de uma aeronave é controlada principalmente por:',
    option_a: 'Os ailerons e o diedro da asa',
    option_b: 'O leme de direção e a deriva vertical',
    option_c: 'O estabilizador horizontal e o leme de profundidade',
    option_d: 'Os flapes e slats',
    correct_answer: 'c',
    difficulty: 'easy',
    explanation: 'A estabilidade longitudinal (em torno do eixo lateral, movimento de cabrar/picar) é controlada pelo estabilizador horizontal (plano fixo) e o leme de profundidade (superfície móvel).'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'A estabilidade direcional de uma aeronave é proporcionada principalmente por:',
    option_a: 'O estabilizador horizontal',
    option_b: 'A deriva vertical (estabilizador vertical) e o leme de direção',
    option_c: 'O diedro das asas',
    option_d: 'Os ailerons diferenciados',
    correct_answer: 'b',
    difficulty: 'easy',
    explanation: 'A estabilidade direcional (em torno do eixo vertical, movimento de guinada) é proporcionada pela deriva vertical. O leme de direção controla o movimento de guinada.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'A estabilidade lateral de uma aeronave é favorecida por:',
    option_a: 'A cauda em T e o alto centro de gravidade',
    option_b: 'O diedro positivo das asas (ângulo ascendente das pontas)',
    option_c: 'A posição avançada do centro de gravidade',
    option_d: 'A elevada razão de aspecto da asa',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'O diedro positivo contribui para a estabilidade lateral: quando a aeronave rola, a asa baixa fica com ângulo de ataque maior, gerando mais sustentação e tendendo a restaurar o voo nivelado.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O centro de pressão (CP) em um perfil alar é:',
    option_a: 'O ponto onde todo o peso da aeronave é concentrado',
    option_b: 'O ponto de aplicação resultante das forças de pressão aerodinâmica',
    option_c: 'O ponto de máxima curvatura do perfil',
    option_d: 'O centro geométrico da asa',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'O centro de pressão é o ponto onde a resultante das forças de pressão aerodinâmica sobre o perfil pode ser considerada como atuando. Ele se move com a variação do ângulo de ataque.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Para que uma aeronave seja estaticamente estável longitudinalmente, o centro de gravidade deve estar:',
    option_a: 'Atrás do centro de pressão',
    option_b: 'À frente do ponto neutro (centro aerodinâmico)',
    option_c: 'Coincidindo com o centro de pressão',
    option_d: 'À frente do bordo de ataque',
    correct_answer: 'b',
    difficulty: 'hard',
    explanation: 'Para estabilidade longitudinal, o CG deve estar à frente do ponto neutro (centro aerodinâmico da aeronave completa). Se o CG estiver atrás, a aeronave será instável longitudinalmente.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O que é o trim de profundidade?',
    option_a: 'Um dispositivo que ajusta a potência do motor automaticamente',
    option_b: 'Uma superfície ajustável que alivia a pressão sobre os controles para manter a atitude desejada',
    option_c: 'Um sistema que bloqueia o leme de profundidade na posição neutra',
    option_d: 'Um dispositivo que aumenta a área do estabilizador horizontal',
    correct_answer: 'b',
    difficulty: 'easy',
    explanation: 'O trim (compensador) de profundidade é uma pequena superfície ajustável no leme de profundidade que permite ao piloto eliminar a pressão necessária sobre o manche para manter a atitude desejada.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O estol em curva (turn stall) é mais perigoso que o estol reto porque:',
    option_a: 'A velocidade de estol é menor do que em voo nivelado',
    option_b: 'A velocidade de estol é maior por causa do fator de carga aumentado e a asa interna pode estolar primeiro',
    option_c: 'Os ailerons perdem eficiência antes de os profundores',
    option_d: 'O motor pode parar durante a curva',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'Em curva, o fator de carga aumenta a velocidade de estol. Adicionalmente, a asa interna (que se move mais lentamente) pode estolar primeiro, causando uma rolagem incontrolável — muito perigoso em baixa altitude.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Qual é o efeito do leme de direção na rolagem?',
    option_a: 'O leme de direção não influencia a rolagem',
    option_b: 'O leme de direção aplicado gera guinada que, por efeito da rolagem adversa, produz também rolagem',
    option_c: 'O leme de direção produz rolagem oposta sempre que aplicado',
    option_d: 'O leme de direção bloqueia os ailerons durante a guinada',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'A aplicação do leme de direção causa guinada, o que gera uma diferença de velocidade entre as asas. Isso produz rolagem na mesma direção da guinada, pois a asa externa se move mais rápido e gera mais sustentação.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Segundo a regulamentação brasileira, o voo acrobático é permitido para pilotos privados sem habilitação específica?',
    option_a: 'Sim, desde que a aeronave seja certificada para acrobacia',
    option_b: 'Sim, em áreas desabitadas e acima de 1.000 pés',
    option_c: 'Não, é necessária habilitação específica em acrobacia aérea',
    option_d: 'Sim, com instrutor a bordo em qualquer situação',
    correct_answer: 'c',
    difficulty: 'easy',
    explanation: 'Conforme o RBAC 61, a realização de voo acrobático requer habilitação específica em acrobacia aérea, além de aeronave certificada para esse fim. Piloto privado sem essa habilitação não pode realizar voos acrobáticos.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'A razão de subida de uma aeronave aumenta quando:',
    option_a: 'O peso aumenta e a altitude diminui',
    option_b: 'O excesso de potência (tração - arrasto) aumenta e o peso diminui',
    option_c: 'O arrasto aumenta junto com a potência',
    option_d: 'A velocidade supera a Vne',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'A razão de subida é determinada pelo excesso de potência disponível sobre a necessária para manutenção do voo nivelado. Mais excesso de potência e menos peso resultam em maior razão de subida.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'A curvatura (camber) de um perfil alar refere-se a:',
    option_a: 'A espessura máxima do perfil em relação à corda',
    option_b: 'A curvatura da linha média do perfil em relação à linha de corda',
    option_c: 'O ângulo de incidência da asa em relação à fuselagem',
    option_d: 'O comprimento total do bordo de ataque ao de fuga',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'A curvatura (camber) é a distância máxima entre a linha média do perfil e a linha de corda. Maior curvatura geralmente significa maior coeficiente de sustentação máxima.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Em voo de descida com potência reduzida e velocidade constante, qual é a relação entre as forças?',
    option_a: 'Sustentação = Peso; Tração = Arrasto',
    option_b: 'Sustentação + Tração = Peso; Arrasto equilibrado por componente do peso',
    option_c: 'Sustentação < Peso; componente do peso ao longo da trajetória equilibra o arrasto menos a tração',
    option_d: 'Peso = Arrasto; Sustentação = Tração',
    correct_answer: 'c',
    difficulty: 'hard',
    explanation: 'Em descida estabilizada, a sustentação é menor que o peso (apenas equilibra a componente perpendicular à trajetória). A componente do peso ao longo da trajetória de descida compensa o arrasto, permitindo menor tração que em voo nivelado.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O arrasto induzido é gerado principalmente por:',
    option_a: 'A rugosidade superficial da aeronave',
    option_b: 'Os vórtices nas pontas de asa resultantes da geração de sustentação',
    option_c: 'A interferência entre a asa e a fuselagem',
    option_d: 'O calor gerado pelo atrito do ar com a superfície',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'O arrasto induzido é um subproduto da geração de sustentação. Os vórtices formados nas pontas de asa (onde o ar de alta pressão da intradorso escapa para a extradorso) criam energia perdida que se manifesta como arrasto.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O arrasto induzido varia com a velocidade da seguinte forma:',
    option_a: 'Aumenta com o quadrado da velocidade',
    option_b: 'É constante independentemente da velocidade',
    option_c: 'Diminui com o quadrado da velocidade (inversamente proporcional a V²)',
    option_d: 'Aumenta linearmente com a velocidade',
    correct_answer: 'c',
    difficulty: 'hard',
    explanation: 'O arrasto induzido é inversamente proporcional ao quadrado da velocidade (Di ∝ 1/V²). Em velocidades baixas é alto; em velocidades altas, é baixo. Já o arrasto parasita se comporta de forma oposta (Dp ∝ V²).'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'A velocidade de mínimo arrasto total (drag) corresponde à velocidade onde:',
    option_a: 'O arrasto induzido é nulo',
    option_b: 'O arrasto parasita é igual ao arrasto induzido',
    option_c: 'O arrasto parasita é o dobro do arrasto induzido',
    option_d: 'O arrasto total é igual ao peso da aeronave',
    correct_answer: 'b',
    difficulty: 'hard',
    explanation: 'O arrasto total mínimo ocorre quando o arrasto parasita iguala o arrasto induzido. Essa velocidade corresponde também à melhor relação L/D e à velocidade de melhor razão de planeio.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Qual é o efeito de aumentar o peso da aeronave na velocidade de estol?',
    option_a: 'Não altera a velocidade de estol',
    option_b: 'Reduz a velocidade de estol',
    option_c: 'Aumenta a velocidade de estol',
    option_d: 'Aumenta a velocidade de estol apenas em configuração limpa',
    correct_answer: 'c',
    difficulty: 'medium',
    explanation: 'Com maior peso, é necessária mais sustentação para manter o voo, o que requer maior velocidade para que o coeficiente de sustentação máximo gere sustentação suficiente. Portanto, a velocidade de estol aumenta com o peso.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O efeito do vento de cauda na performance de decolagem é:',
    option_a: 'Melhora a performance, reduzindo a distância de decolagem',
    option_b: 'Não tem efeito significativo na distância de decolagem',
    option_c: 'Prejudica a performance, aumentando a distância de decolagem',
    option_d: 'Aumenta a razão de subida após a decolagem',
    correct_answer: 'c',
    difficulty: 'easy',
    explanation: 'Vento de cauda reduz a velocidade do ar sobre as asas para uma dada velocidade solo, exigindo maior velocidade solo para atingir a velocidade de decolagem. Isso aumenta a distância de decolagem.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'A razão de aspecto (aspect ratio) de uma asa é:',
    option_a: 'A relação entre a espessura e a corda do perfil',
    option_b: 'A relação entre a envergadura e a corda média (b/c)',
    option_c: 'O ângulo de curvatura da asa em relação ao horizonte',
    option_d: 'A proporção entre a área superior e inferior do perfil',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'A razão de aspecto é AR = b²/S (ou b/c para corda constante), onde b é a envergadura e S é a área alar. Razão de aspecto alta (asa longa e estreita) resulta em menor arrasto induzido.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Em qual situação o efeito P-factor é mais acentuado?',
    option_a: 'Durante o voo de cruzeiro em altitude de serviço',
    option_b: 'Durante a decolagem com potência máxima e alto ângulo de ataque',
    option_c: 'Durante a aproximação final com potência reduzida',
    option_d: 'Com vento de proa forte',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'O P-factor é máximo quando combinados: alto ângulo de ataque (pá descendente incide com maior ângulo) e potência máxima. A decolagem reúne ambas as condições.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O que é a velocidade Vg?',
    option_a: 'A velocidade de glide (planeio) com melhor razão de planeio',
    option_b: 'A velocidade de referência de pouso',
    option_c: 'A velocidade máxima de guinada',
    option_d: 'A velocidade de cruzeiro com motor em repouso',
    correct_answer: 'a',
    difficulty: 'medium',
    explanation: 'Vg (Best Glide Speed) é a velocidade que proporciona a melhor razão de planeio, ou seja, a maior distância horizontal para cada unidade de altitude perdida. Usada em emergência com motor parado.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Durante uma subida, o equilíbrio de forças na aeronave é tal que:',
    option_a: 'Tração = Arrasto; Sustentação = Peso',
    option_b: 'Tração > Arrasto + componente do peso na trajetória; Sustentação = componente do peso perpendicular à trajetória',
    option_c: 'Sustentação > Peso; Tração = Arrasto',
    option_d: 'Peso = Tração; Sustentação = Arrasto',
    correct_answer: 'b',
    difficulty: 'hard',
    explanation: 'Em subida estabilizada, a tração deve superar o arrasto mais a componente do peso na direção oposta à trajetória. A sustentação só equilibra a componente do peso perpendicular à trajetória (que é menor que o peso total).'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'A extradorso de um perfil alar refere-se a:',
    option_a: 'A superfície inferior (intrados) da asa',
    option_b: 'A superfície superior da asa (região de baixa pressão)',
    option_c: 'A região entre o bordo de ataque e o ponto de máxima espessura',
    option_d: 'O bordo de fuga da asa',
    correct_answer: 'b',
    difficulty: 'easy',
    explanation: 'A extradorso é a superfície superior do perfil alar. É nela que ocorre a aceleração do ar e a redução de pressão responsável pela maior parte da sustentação gerada.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O que ocorre com a velocidade de estol quando os flapes são estendidos?',
    option_a: 'A velocidade de estol aumenta significativamente',
    option_b: 'A velocidade de estol não se altera',
    option_c: 'A velocidade de estol diminui pois o CL máximo aumenta',
    option_d: 'A velocidade de estol depende apenas do peso, não dos flapes',
    correct_answer: 'c',
    difficulty: 'medium',
    explanation: 'Os flapes aumentam o coeficiente de sustentação máximo (CL máx), permitindo que a aeronave sustente-se a velocidades menores. Assim, a velocidade de estol com flapes (Vs0) é menor que sem flapes (Vs1).'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O que acontece ao puxar abruptamente o manche para cima a alta velocidade em relação ao fator de carga?',
    option_a: 'O fator de carga diminui pois a sustentação diminui momentaneamente',
    option_b: 'O fator de carga aumenta abruptamente podendo exceder os limites estruturais',
    option_c: 'O fator de carga permanece em 1 até ocorrer o estol',
    option_d: 'O fator de carga aumenta gradualmente de forma segura',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'Puxar o manche abruptamente a alta velocidade gera aumento súbito de ângulo de ataque e sustentação, resultando em alto fator de carga instantâneo que pode exceder os limites estruturais da aeronave.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Em qual das condições a seguir o arrasto parasita é maior?',
    option_a: 'Voo lento com alta sustentação',
    option_b: 'Voo rápido em cruzeiro de alta velocidade',
    option_c: 'Planeio com hélice parada',
    option_d: 'Decolagem com flapes parcialmente estendidos',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'O arrasto parasita (perfil, interferência, forma) é proporcional ao quadrado da velocidade (Dp ∝ V²). Portanto, é máximo em velocidades altas de cruzeiro.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O que é o ângulo de incidência da asa?',
    option_a: 'O ângulo de ataque em condições de cruzeiro',
    option_b: 'O ângulo fixo entre a linha de corda da asa e o eixo longitudinal da fuselagem',
    option_c: 'O ângulo entre a asa e o horizonte durante o voo',
    option_d: 'O ângulo do diedro entre as duas asas',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'O ângulo de incidência é o ângulo fixo, definido em projeto, entre a linha de corda da asa e o eixo longitudinal da fuselagem. Diferente do ângulo de ataque, que varia com a atitude.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O fator de carga limite positivo para uma aeronave da categoria normal (RBAC 23) é:',
    option_a: '2,5 g',
    option_b: '3,8 g',
    option_c: '4,4 g',
    option_d: '6,0 g',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'Para aeronaves da categoria normal conforme RBAC 23, o fator de carga limite positivo mínimo é de 3,8 g. Para categoria utilitária é 4,4 g e acrobática é 6,0 g.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O que é o ponto neutro de uma aeronave?',
    option_a: 'O ponto onde a sustentação é zero',
    option_b: 'O centro aerodinâmico da aeronave completa — ponto em torno do qual o momento de arfagem não varia com o ângulo de ataque',
    option_c: 'O ponto de equilíbrio de peso em voo nivelado',
    option_d: 'O centro geométrico da fuselagem',
    correct_answer: 'b',
    difficulty: 'hard',
    explanation: 'O ponto neutro é o centro aerodinâmico de toda a aeronave. Para estabilidade longitudinal, o CG deve estar à frente do ponto neutro. A margem estática é a distância entre o CG e o ponto neutro.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O que caracteriza uma aeronave estaticamente instável longitudinalmente?',
    option_a: 'Após um distúrbio, a aeronave retorna espontaneamente à atitude original',
    option_b: 'A aeronave requer ajuste constante de trim para manter atitude',
    option_c: 'Após um distúrbio, a aeronave tende a se afastar ainda mais da atitude original',
    option_d: 'A aeronave mantém a nova atitude após o distúrbio sem tendência de retorno ou afastamento',
    correct_answer: 'c',
    difficulty: 'hard',
    explanation: 'Uma aeronave estaticamente instável, após sofrer um distúrbio, tende a se afastar progressivamente da atitude de equilíbrio, exigindo intervenção constante do piloto.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Qual é o efeito da altitude elevada na performance da aeronave com motor atmosférico?',
    option_a: 'A performance melhora com menor densidade do ar',
    option_b: 'A performance piora: menor densidade reduz potência do motor e aumenta a velocidade indicada de estol',
    option_c: 'Não há efeito da altitude na performance de voo',
    option_d: 'O motor produz mais potência em altitude por menor resistência do ar',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'Em altitude elevada, a menor densidade do ar reduz a potência de motores atmosféricos e aumenta a velocidade real de estol (embora o velocímetro, que mede pressão dinâmica, ainda indique a mesma velocidade indicada de estol).'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O que é o arrasto de interferência?',
    option_a: 'O arrasto causado pelo ruído eletromagnético na instrumentação',
    option_b: 'O arrasto adicional criado pela junção de componentes da aeronave (asa-fuselagem, struts, etc.)',
    option_c: 'O arrasto que interfere na trajetória de cruzeiro',
    option_d: 'O arrasto gerado pela antena de rádio',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'O arrasto de interferência resulta da perturbação dos campos de fluxo onde componentes da aeronave se encontram, como a junção asa-fuselagem. É parte do arrasto parasita total.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O que ocorre com a velocidade de estol se a aeronave voa em uma curva com inclinação de 45°?',
    option_a: 'A velocidade de estol é igual à de voo nivelado',
    option_b: 'A velocidade de estol é aproximadamente 19% maior (fator de carga = 1/cos45° ≈ 1,41)',
    option_c: 'A velocidade de estol é 45% maior',
    option_d: 'A velocidade de estol dobra',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'Para 45° de inclinação: n = 1/cos(45°) = 1/0,707 ≈ 1,41. Vs_n = Vs × √1,41 ≈ Vs × 1,19. Portanto, a velocidade de estol aumenta cerca de 19%.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O que é o diedro negativo (anhedral) e qual seu efeito na estabilidade?',
    option_a: 'Asas com pontas voltadas para cima; aumenta a estabilidade lateral',
    option_b: 'Asas com pontas voltadas para baixo; reduz a estabilidade lateral e é usado para melhorar a manobrabilidade',
    option_c: 'Ângulo de torção da ponta da asa; reduz o arrasto induzido',
    option_d: 'Ângulo de varredura da asa; melhora desempenho em alta velocidade',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'O diedro negativo (anhedral) tem as pontas das asas voltadas para baixo. Reduz a estabilidade lateral, mas melhora a manobrabilidade em rolamento, sendo usado em caças e aviões de alta performance.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O que é o Vórtice de ponta de asa e como ele afeta o desempenho?',
    option_a: 'É uma turbulência em torno do bordo de ataque que aumenta a sustentação',
    option_b: 'É uma turbulência circular nas extremidades da asa que gera arrasto induzido e reduz a eficiência',
    option_c: 'É o fluxo laminar ideal que maximiza a sustentação',
    option_d: 'É um efeito benéfico que reduz o arrasto de perfil',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'Os vórtices de ponta de asa são redemoinhos criados pelo ar que escapa da intradorso (alta pressão) para a extradorso (baixa pressão). Geram arrasto induzido, reduzindo a eficiência. Winglets ajudam a minimizá-los.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Em que condição o arrasto induzido é máximo?',
    option_a: 'Alta velocidade e baixo ângulo de ataque',
    option_b: 'Baixa velocidade e alto coeficiente de sustentação (próximo ao estol)',
    option_c: 'Com flapes totalmente recolhidos',
    option_d: 'Durante o voo nivelado de cruzeiro',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'O arrasto induzido é proporcional ao quadrado do coeficiente de sustentação (Cl²) e inversamente proporcional à V². Em baixas velocidades e alto CL (perto do estol), o arrasto induzido é máximo.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Uma aeronave com CG muito à frente do limite dianteiro pode apresentar:',
    option_a: 'Instabilidade longitudinal e tendência de cabrar',
    option_b: 'Maior dificuldade em cabrar, exigindo mais força no manche e maior velocidade de estol',
    option_c: 'Melhora na estabilidade e redução da velocidade de estol',
    option_d: 'Estol mais suave e facilidade de recuperação',
    correct_answer: 'b',
    difficulty: 'hard',
    explanation: 'Com CG muito avançado, o braço de alavanca do estabilizador é curto e o momento de cabrar é grande. O piloto precisa de maior deflexão do leme de profundidade para cabrar, e a velocidade de estol pode aumentar pois o estabilizador gera força para baixo.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Uma aeronave com CG muito atrás do limite traseiro pode apresentar:',
    option_a: 'Dificuldade em picar o nariz',
    option_b: 'Instabilidade longitudinal e tendência de cabrar de forma difícil de controlar',
    option_c: 'Maior estabilidade e melhor desempenho em cruzeiro',
    option_d: 'Redução do arrasto e maior velocidade de cruzeiro',
    correct_answer: 'b',
    difficulty: 'hard',
    explanation: 'Com CG atrás do limite traseiro, a aeronave fica instável longitudinalmente. Qualquer perturbação que aumente o ângulo de ataque levará a aeronave a cabrar ainda mais, podendo resultar em estol irrecuperável.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O que é a velocidade de envoltura (Mach crítico) e por que é relevante para aeronaves de aviação geral?',
    option_a: 'É a velocidade em que a aeronave pode voar em segurança em nuvens de gelo',
    option_b: 'É a velocidade em que primeiro aparecem zonas de fluxo supersônico local na asa, causando ondas de choque',
    option_c: 'É a velocidade máxima com o trem de pouso abaixado',
    option_d: 'É a velocidade em que os flapes podem ser usados',
    correct_answer: 'b',
    difficulty: 'hard',
    explanation: 'O Mach crítico é a velocidade de voo em que a velocidade do ar sobre alguma parte da aeronave (geralmente o ponto de máxima curvatura da asa) atinge Mach 1 localmente. Para aviação geral subsônica, é uma limitação operacional importante em aeronaves de alta velocidade.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Em voo nivelado, ao aumentar a velocidade mantendo altitude constante, o ângulo de ataque:',
    option_a: 'Aumenta para gerar mais sustentação',
    option_b: 'Diminui, pois menor ângulo de ataque gera a mesma sustentação em maior velocidade',
    option_c: 'Permanece constante',
    option_d: 'Varia apenas com o peso da aeronave',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'Em voo nivelado constante, a sustentação deve igualar o peso. Com maior velocidade, o ar gera mais sustentação por unidade de ângulo de ataque, então o ângulo de ataque deve diminuir para manter sustentação = peso.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O que é o "wash-out" (torção geométrica negativa) de uma asa?',
    option_a: 'A lavagem do fluxo de ar na popa da aeronave',
    option_b: 'A torção da asa que diminui o ângulo de incidência em direção à ponta, prevenindo estol prematuro das pontas',
    option_c: 'A remoção de gelo acumulado nas asas',
    option_d: 'O efeito de limpeza do fluxo laminar sobre a asa',
    correct_answer: 'b',
    difficulty: 'hard',
    explanation: 'O wash-out (torção geométrica negativa) é o design em que o ângulo de incidência diminui da raiz para a ponta da asa. Isso garante que a raiz estole antes da ponta, mantendo eficácia dos ailerons durante o estol.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O que ocorre com a estabilidade direcional quando o CG está muito atrás dos limites?',
    option_a: 'Aumenta pois há maior braço de momento para a deriva vertical',
    option_b: 'Não é afetada pela posição do CG',
    option_c: 'Diminui pois a cauda fica com menor efetividade',
    option_d: 'A estabilidade direcional aumenta enquanto a longitudinal diminui',
    correct_answer: 'c',
    difficulty: 'hard',
    explanation: 'Com CG muito atrás, o braço de momento entre o CG e a deriva vertical diminui, reduzindo a efetividade restauradora da cauda em movimento direcional, comprometendo a estabilidade direcional.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'A oscilação holandesa (Dutch Roll) é caracterizada por:',
    option_a: 'Uma oscilação em rolamento puro sem guinada',
    option_b: 'Uma oscilação acoplada de rolamento e guinada, típica de asas com grande varredura',
    option_c: 'Uma oscilação longitudinal com cabrar e picar alternados',
    option_d: 'Uma vibração da estrutura em frequências ressonantes',
    correct_answer: 'b',
    difficulty: 'hard',
    explanation: 'A oscilação holandesa é uma oscilação dinâmica acoplada de guinada e rolamento. É mais comum em aeronaves com asas de grande varredura e pode ser amortecida por yaw dampers.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O movimento espiral (spiral divergence) de uma aeronave ocorre quando:',
    option_a: 'A estabilidade lateral é muito forte e a direcional é fraca',
    option_b: 'A estabilidade direcional é forte e a lateral é fraca, levando à inclinação crescente em curva',
    option_c: 'A aeronave entra em estol durante uma curva fechada',
    option_d: 'O piloto aplica leme oposto ao aileron em uma curva',
    correct_answer: 'b',
    difficulty: 'hard',
    explanation: 'A divergência espiral ocorre quando a estabilidade direcional predomina sobre a lateral: após uma perturbação em rolamento, a forte tendência de guinada leva a asa baixa a gerar mais sustentação, aumentando a inclinação progressivamente.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Qual é a diferença entre estabilidade estática e dinâmica?',
    option_a: 'Estática refere-se ao voo em formação; dinâmica ao voo solo',
    option_b: 'Estabilidade estática é a tendência inicial de retorno após distúrbio; dinâmica é o comportamento ao longo do tempo',
    option_c: 'Estática é medida em solo; dinâmica é medida em voo',
    option_d: 'São sinônimos que descrevem o mesmo fenômeno',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'Estabilidade estática é a tendência inicial (retorno, neutralidade ou afastamento) após um distúrbio. Estabilidade dinâmica descreve o comportamento ao longo do tempo (oscilações amortecidas, neutras ou crescentes).'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Uma aeronave estaticamente estável pode ser dinamicamente instável?',
    option_a: 'Não, são sempre combinadas',
    option_b: 'Sim, pode retornar inicialmente à posição de equilíbrio mas com oscilações crescentes ao longo do tempo',
    option_c: 'Não, estabilidade dinâmica implica necessariamente estabilidade estática e vice-versa',
    option_d: 'Apenas em condições de alta altitude',
    correct_answer: 'b',
    difficulty: 'hard',
    explanation: 'Uma aeronave pode ser estaticamente estável (tendência inicial correta) mas dinamicamente instável (oscilações que crescem com o tempo). O contrário — estaticamente instável mas dinamicamente estável — não é possível.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'A "phugoid" é um modo de oscilação que envolve:',
    option_a: 'Oscilações rápidas de ângulo de ataque com pouca variação de velocidade',
    option_b: 'Oscilações lentas de velocidade e altitude com ângulo de ataque aproximadamente constante',
    option_c: 'Oscilações em rolamento com frequência baixa',
    option_d: 'Oscilações do trem de pouso durante o toque',
    correct_answer: 'b',
    difficulty: 'hard',
    explanation: 'O modo phugoid (ou fugóide) é uma oscilação longitudinal de longo período onde a aeronave troca energia cinética por potencial: acelera ao descer e desacelera ao subir, mantendo o ângulo de ataque aproximadamente constante.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O que acontece com o empuxo de uma hélice quando a aeronave atinge velocidades mais altas?',
    option_a: 'O empuxo aumenta com a velocidade',
    option_b: 'O empuxo permanece constante independentemente da velocidade',
    option_c: 'O empuxo diminui com o aumento de velocidade para uma dada rotação',
    option_d: 'O empuxo dobra com o quadrado da velocidade',
    correct_answer: 'c',
    difficulty: 'medium',
    explanation: 'Para uma dada rotação, o empuxo da hélice diminui com o aumento da velocidade de voo, pois a velocidade relativa do ar em relação às pás diminui. Isso explica por que a razão de subida diminui em velocidades acima de Vy.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O que é o "ground effect" (efeito solo) e qual altitude é significativa?',
    option_a: 'Ocorre a qualquer altitude e aumenta o consumo de combustível',
    option_b: 'Ocorre abaixo de uma altura aproximada igual à envergadura da asa, reduzindo o arrasto induzido',
    option_c: 'Ocorre apenas durante o pouso e aumenta o arrasto',
    option_d: 'Ocorre em altitude de cruzeiro e afeta apenas o estabilizador',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'O efeito solo é significativo abaixo de uma altitude aproximadamente igual à envergadura da asa (b). Nessa zona, o solo restringe a formação de vórtices de ponta de asa, reduzindo o arrasto induzido.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Durante o flare (arredondamento) no pouso, o efeito solo contribui para:',
    option_a: 'Aumentar o arrasto e forçar a aeronave ao solo rapidamente',
    option_b: 'Fazer a aeronave "flutuar" mais do que esperado ao reduzir o arrasto induzido',
    option_c: 'Aumentar a velocidade de estol significativamente',
    option_d: 'Reduzir a eficiência dos flapes no pouso',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'O efeito solo reduz o arrasto induzido próximo ao solo, fazendo a aeronave "flutuar" mais do que o esperado durante o flare. Com vento de cauda, esse efeito pode ser especialmente pronunciado.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Qual das seguintes afirmações sobre flapes Fowler está CORRETA?',
    option_a: 'São flapes simples que apenas se deflectem para baixo',
    option_b: 'Aumentam apenas o arrasto sem aumentar a área alar',
    option_c: 'Ao estenderem, movem-se para trás aumentando a área alar e a curvatura, gerando mais sustentação com relativo baixo arrasto inicial',
    option_d: 'São usados somente para controle de rolagem em baixa velocidade',
    correct_answer: 'c',
    difficulty: 'medium',
    explanation: 'Os flapes Fowler se deslocam para trás (aumentando a corda e área alar) e para baixo (aumentando a curvatura). Nas primeiras deflexões, proporcionam grande aumento de sustentação com pouco arrasto adicional.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O coeficiente de sustentação (CL) de um perfil alar é afetado por:',
    option_a: 'Apenas pela velocidade do voo',
    option_b: 'Pelo ângulo de ataque, formato do perfil e Reynolds number',
    option_c: 'Apenas pelo peso da aeronave',
    option_d: 'Apenas pela altitude de voo',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'O coeficiente de sustentação (CL) depende do ângulo de ataque (principal fator), da geometria do perfil alar (curvatura, espessura) e do número de Reynolds (que relaciona velocidade, densidade e viscosidade do ar).'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O que é o "boundary layer" (camada limite) na aerodinâmica?',
    option_a: 'A altitude máxima de operação da aeronave',
    option_b: 'A fina camada de ar adjacente à superfície onde os efeitos de viscosidade são importantes',
    option_c: 'O limite entre o fluxo laminar e turbulento da hélice',
    option_d: 'A região de pressão máxima na intradorso da asa',
    correct_answer: 'b',
    difficulty: 'hard',
    explanation: 'A camada limite é a região fina de ar próxima à superfície da asa onde a velocidade varia de zero (na superfície) ao valor do fluxo livre. A separação da camada limite é o mecanismo fundamental do estol.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Em que tipo de fluxo a camada limite tende a se separar mais facilmente do perfil?',
    option_a: 'Fluxo turbulento',
    option_b: 'Fluxo laminar',
    option_c: 'Fluxo supersônico',
    option_d: 'A separação independe do tipo de fluxo',
    correct_answer: 'b',
    difficulty: 'hard',
    explanation: 'O fluxo laminar, embora menos resistente, é mais suscetível à separação em gradientes adversos de pressão. O fluxo turbulento tem mais energia e resiste melhor à separação, embora gere mais arrasto de atrito.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O que é o "stagnation point" (ponto de estagnação)?',
    option_a: 'O ponto de máxima velocidade do ar sobre a asa',
    option_b: 'O ponto no bordo de ataque onde o fluxo se divide entre extradorso e intradorso com velocidade relativa zero',
    option_c: 'O ponto de mínima pressão na asa',
    option_d: 'O ponto de máxima curvatura do perfil',
    correct_answer: 'b',
    difficulty: 'hard',
    explanation: 'O ponto de estagnação é onde o fluxo de ar se divide no bordo de ataque. Nesse ponto, a velocidade relativa do ar é zero e a pressão é máxima (pressão de estagnação). Sua posição muda com o ângulo de ataque.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'Como a temperatura do ar afeta a performance do motor a pistão?',
    option_a: 'Ar mais quente é mais denso e melhora a potência',
    option_b: 'Ar mais quente é menos denso, reduzindo a quantidade de oxigênio e a potência do motor',
    option_c: 'A temperatura não afeta a potência, apenas a viscosidade',
    option_d: 'Ar mais frio reduz a potência por maior densidade',
    correct_answer: 'b',
    difficulty: 'easy',
    explanation: 'Ar quente tem menor densidade (menor quantidade de moléculas por volume), o que reduz a quantidade de oxigênio disponível para combustão. Isso diminui a potência máxima de motores atmosféricos.'
  },
  {
    bloco_id: 'teoria_de_voo',
    text: 'O que é a altitude-densidade (density altitude) e como afeta a performance?',
    option_a: 'A altitude real acima do nível do mar; não afeta a performance',
    option_b: 'A altitude à qual a densidade padrão seria encontrada; alta altitude-densidade reduz performance',
    option_c: 'A altitude mínima de voo sobre obstáculos; determina a rota',
    option_d: 'A altitude registrada pelo altímetro barométrico calibrado',
    correct_answer: 'b',
    difficulty: 'medium',
    explanation: 'Altitude-densidade é a altitude na atmosfera padrão correspondente à densidade atual do ar. Temperatura alta e pressão baixa aumentam a altitude-densidade, reduzindo a performance de motores e asas.'
  },
];
